module.exports = [
    {'name': 'abscesso', 'description': 'constitui uma coleção de pus ou material purulento, comumente associado a uma infecção bacteriana'},
    {'name': 'abulia', 'description': 'perturbação ou Alteração fisiopatológica caracterizada por diminuição ou supressão da vontade'},
    {'name': 'acalásia', 'description': 'compreende a ausência de relaxamento dos esfíncteres. Comumente decorrente de distúrbio nervoso ou por causa desconhecida'},
    {'name': 'acrocianose', 'description': 'distúrbio circulatório que manifesta-se em extremidades tornando-as frias e de coloração azulada. Ocorre principalmente em mãos, e menos comumente os pés, algumas manifestações de acrocianose estão associadas ao fenômeno de Raynaud'},
    {'name': 'acrocórdons', 'description': 'também chamados de pólipos cutâneos, são crescimentos exagerados da pele normal que formam uma haste e são parecidos com pólipos'},
    {'name': 'acromegalia', 'description': 'é um distúrbio representado pelo aumento desproporcional dos membros e face, associados a hiperfunção da hipófise'},
    {'name': 'adenite', 'description':  'inflamação ou ingurgitamento de uma glândula ou gânglio linfático'},
    {'name': 'adenomegalia', 'description': ' hipertrofia de um gânglio linfático'},
    {'name': 'adipsia', 'description': 'falta de sede'},
    {'name': 'aerofagia', 'description': 'ato de deglutir ar Acomete algumas pessoas, especialmente as que sofrem de dispepsia ou de certos estados ansiosos, neuróticos ou mesmo em situações que levem um indivíduo à uma agitação física e psíquica'},
    {'name': 'afagia', 'description': 'impossibilidade de deglutir'},
    {'name': 'afasia', 'description': 'sintoma neurológico revelado por perda ou incapacidade de expressar ou interpretar a linguagem falada ou escrita'},
    {'name': 'afebril', 'description': 'sem febre'},
    {'name': 'aférese', 'description': 'remoção do sangue do próprio paciente'},
    {'name': 'agalactia', 'description': 'ausência de leite nas mamas depois do parto; agalactose'},
    {'name': 'ageusia', 'description': 'ausência ou redução do sentido do paladar'},
    {'name': 'aglossia', 'description': 'ausência congênita da língua'},
    {'name': 'agnosia', 'description': 'é uma perturbação que se caracteriza pelo fato de a pessoa poder ver e sentir os objetos'},
    {'name': 'agorafobia', 'description': 'distúrbio caracterizado pela sensação de medo de estar só em espaço aberto'},
    {'name': 'agrafia', 'description': 'é uma incapacidade para traduzir as idéias por escrito, apesar de não haver nenhum comprometimento psicomotor, da fala ou da compreensão'},
    {'name': 'alodinia', 'description': 'envolve uma mudança no sentido da dor, da qualidade de uma sensação, seja do tipo que for'},
    {'name': 'alopécia', 'description': 'é a redução parcial ou total de pelos ou cabelos em uma determinada área de pele'},
    {'name': 'amaurose', 'description': 'é a perda total da visão'},
    {'name': 'amenorreia', 'description': 'ausência de mestruação'},
    {'name': 'anacusia', 'description': 'total perda da capacidade auditiva'},
    {'name': 'anafrodisia', 'description': 'corresponde a falta de desejo sexual. Frigidez'},
    {'name': 'analgesia', 'description': 'perda ou ausência de sensibilidade dolorosa'},
    {'name': 'anasarca', 'description': 'acúmulo generalizado de líquidos entre os tecidos ou edema generalizado'},
    {'name': 'anastomose', 'description': 'união entre estruturas tubulares'},
    {'name': 'anciloglossia', 'description': 'encurtamento do frênulo da língua'},
    {'name': 'anestesia', 'description': 'ausência de sensibilidade tátil'},
    {'name': 'aneurisma', 'description': 'alargamento de forma anormal da luz de um vaso sanguíneo'},
    {'name': 'angina', 'description': 'termo médico utilizado para se referir à sensação opressiva que decorre da falta de oxigênaçã do músculo cardíaco'},
    {'name': 'anisocoria', 'description': 'tamnho desigual ds pupilas'},
    {'name': 'anorexia', 'description': 'distúrbio alimentar que leva a pessoa a ter uma visão distorcida do seu corpo'},
    {'name': 'anosmia', 'description': 'diminuição ouperda total do olfato'},
    {'name': 'anquiloglossia', 'description': 'distúrbio de desenvolvimento revelado pela presença de freio lingual curto, leva ao fenômeno conhecido como língua presa'},
    {'name': 'anquilose', 'description': 'imobilidade de uma articulação'},
    {'name': 'anúria', 'description': 'ausência de secreção urinária'},
    {'name': 'apnéia do sono', 'description': 'é um distúrbio do sono potencialmente grave em que a respiração cessa e começa repetidamente'},
    {'name': 'apneia', 'description': 'supressão momentânea da respiração'},
    {'name': 'apraxia', 'description': 'é um distúrbio neurológico revelado pela incapacidade de executar movimentos coordenados'},
    {'name': 'artralgia', 'description': 'dor em articulações'},
    {'name': 'artrite', 'description': 'inflamação que acomete articulações'},
    {'name': 'artrose', 'description': 'condição degenerativa representada pelo adelgaçamento ou destruição da cartilagem articular e deformação das superfície óssea de uma ou mais articulações'},
    {'name': 'ascite', 'description': 'acúmulo anormal de líquidos dentro da cavidade peritoneal'},
    {'name': 'astenia', 'description': 'ausência ou perda de força muscular'},
    {'name': 'ataxia', 'description': 'falta de coordenação de movimentos musculares voluntaries ou mesmo de equilíbrio'},
    {'name': 'atetose', 'description': 'consequência de lesões centrais, caracterizada por apresentar movimentos irregulares e arrítmicos de mãos, pés associado a distensões e contrações dos dedos'},
    {'name': 'atresia', 'description': 'estreitamento ou oclusão de qualquer canal do corpo'},
    {'name': 'atrofia', 'description': 'perda de massa muscular'},
    {'name': 'baqueamento digital' , 'description': 'conhecido também por unhas em Vidro de relógio ou hipocráticas. Ocorre quando o ângulo do leito ungueal é maior que 180 graus. Comun em doenças que comprometem a circulação pulmonar'},
    {'name': 'blefarite', 'description': 'inflamação das pálpebras'},
    {'name': 'bócio', 'description': 'aumento de volume crônico da tireoide que ocorre em algumas regiões do mundo com dieta pobre em iodo'},
    {'name': 'bolha', 'description': 'termo semiológico que se refere à uma lesão elevada, maior que 1 cm de diâmetro e que apresenta acúmulo de liquido de aspecto claro ou citrino. Ocorre prevalentemente entre as camadas superficiais da epiderme ou mucosa'},
    {'name': 'bradicardia', 'description': 'diminuição da frequência cardíaca a menos de 60 batimentos por minuto'},
    {'name': 'bradicinesia', 'description': 'termo médico que define a lentidão anormal dos movimentos'},
    {'name': 'bradipneia', 'description': 'respiração lenta. Frequência ventilatória diminuída, abaixo de 8 inspirações por minuto'},
    {'name': 'bulimia', 'description': 'é a ingesta compulsiva de alimentos, comumente seguida de indução de vômitos'},
    {'name': 'cacifo', 'description': 'sinal clinico avaliado por meio de pressão digital sobre um edema de pele. Considera-se cacifo positivo em áreas onde a compressão não se desfaz imediatamente após a remoção da pressão digital'},
    {'name': 'cacofagia', 'description': 'estado mórbido em que o paciente apresenta perversão do apetite, fazendo-o ingerir substâncias consideradas repugnantes, como exemplo fezes'},
    {'name': 'cacosmia', 'description': 'indivíduo que aprecia ou sente atração por cheiros desagradáveis'},
    {'name': 'calázio', 'description': 'condição inflamatória caracterizada por pequeno nódulo localizado em região inferior ou superior das pálpebras causado pelo bloqueio dos orifícios das glândulas palpebrais'},
    {'name': 'calvície', 'description': 'também denominada de alopécia androgênica. É uma afecção, comum no homem e rara na mulher, representada por perda de cabelos'},
    {'name': 'canície', 'description': 'despigmentação capilar que surge fisiologicamente a partir da terceira década de vida'},
    {'name': 'caquexia', 'description': 'emagrecimento extremo com comprometimento franco do estado geral e incapacidade de desempenhar atividades mínimas'},
    {'name': 'catatonia', 'description': 'quadro clinico onde ocorre uma perturbação da iniciativa e comportamento motor, bem como do grau de tensão muscular. É comum em transtornos psiquiátricos'},
    {'name': 'cefaleia', 'description': 'dor de cabeça'},
    {'name': 'celulite', 'description': 'inflamação de tecido conjuntivo subcutâneo frouxo'},
    {'name': 'ceratite', 'description': 'inflamação na córnea'},
    {'name': 'ceratocone', 'description': 'é uma condição patológica que afeta o formato e a espessura da córnea, como resultado, o paciente apresenta percepção distorcida de imagens'},
    {'name': 'cervicalgia', 'description': 'dor localizada na região cervical, isto é na parte posterior do pescoço ou nuca'},
    {'name': 'cervicite', 'description':  'inflamação localizada no colo uterino'},
    {'name': 'choque anafilático', 'description': 'constitui uma reação alérgica grave, resultando em diminuição da pressão arterial, taquicardia, acompanhado ou não de edema de glote'},
    {'name': 'choque séptico', 'description':'é o termo médico utilizado para designar a falência circulatório aguda por causa infecciosa'},
    {'name': 'choque', 'description': 'sofrimento celular fruto da falta de irrigação sanguínea'},
    {'name': 'cianose', 'description': 'sinal onde o paciente apresenta cor azulada ou arroxeada da pele e das mucosas, decorrente da diminuição da oxigenação tecidual'},
    {'name': 'cistite', 'description': 'inflamação da bexiga'},
    {'name': 'cisto', 'description': 'cavidade encapsulada cheia de líquido na derme ou camada subcutânea, elevando a pele sob tensão'},
    {'name': 'claudicação', 'description': 'é um termo médico para designar distúrbio de marcha devido a diferenças anatômicas ou funcionais entre os membros inferiores'},
    {'name': 'cloasma', 'description': 'é uma área acastanhada irregular de hiper-pigmentação na face'},
    {'name': 'clônus', 'description': 'série de contrações involuntárias devido a um estiramento súbito do músculo'},
    {'name': 'coiloníquia', 'description': 'unha em forma de colher'},
    {'name': 'coitarca', 'description': 'idade da primeira atividade sexual'},
    {'name': 'colêmese', 'description': 'vômito com bile'},
    {'name': 'colestase', 'description': 'iminuição ou interrupção do fluxo da bilis como resultado de retenção do conteúdo biliar no parênquima hepático.'},
    {'name': 'colite', 'description': 'inflamação do cólon'},
    {'name': 'conjuntivite', 'description': 'inflamação da conjuntiva'},
    {'name': 'constipação', 'description': 'afecção produzida por alteração de transito intestinal, gerando retenção de fezes ou dificuldade de sua evacuação'},
    {'name': 'coriza', 'description': 'corrimento de secreção nasal'},
    {'name': 'criptoquirdia', 'description': 'testículos não descidos'},
    {'name': 'dacriocistite', 'description':  'inflamação do saco nasolacrimal'},
    {'name': 'delírio', 'description': 'Alteração aguda da consciência ou da lucidez, fruto de um distúrbio orgânica'},
    {'name': 'derrame pleural', 'description': 'acúmulo de líquido no espaço pleural do tórax'},
    {'name': 'derrame', 'description': 'Acúmulo anormal de liquido em qualquer cavidade ou órgão'},
    {'name': 'diarréia', 'description': 'Tecnicamente consiste em evacuação de mais de 200 g de fezes ao dia. É uma também uma perturbação intestinal caracterizada por aumento frequência de evacuações'},
    {'name': 'diérese', 'description': 'Segmentação de fragmentos de tecidos orgânicos normalmente unidas, de forma acidental ou cirúrgica, sem perda de substância'},
    {'name': 'diplopia', 'description': 'Presença de visão dupla relatada pelo paciente, ocorre comumente em estrabismo'},
    {'name': 'disacusia', 'description': 'Estado mórbido em que sons produzem distúrbio da audição, dor ou mal-estar'},
    {'name': 'disartria', 'description': 'dificuldade na articulação da fala'},
    {'name': 'disdiadococinesia', 'description': 'Incapacidade de realizar eficientemente movimentos rápidos e alternados. Ocorre comumente em doença cerebelar'},
    {'name': 'disenteria', 'description': 'Diarréia com a presença de muco, pus ou sangue nas fezes e dor à evacuação'},
    {'name': 'disfagia', 'description': 'Distúrbio em que o paciente apresenta dificuldade de deglutição'},
    {'name': 'disfasia', 'description': 'Perturbação na compreensão ou expressão da linguagem'},
    {'name': 'disfonia', 'description': 'Alteração ou dificuldade da produção normal da voz'},
    {'name': 'dislalia', 'description': 'é um distúrbio da fala, caracterizado pela dificuldade em articular as palavras. Basicamente consiste na má pronúncia das palavras, seja omitindo ou acrescentando fonemas, trocando um fonema por outro ou ainda distorcendo-os ordenadamente'},
    {'name': 'dislexia', 'description': 'Disfasia escrita ou dificuldade de leitura, apesar da visão e da articulação das palavras apresentarem-se normais. Resulta de um defeito da habilidade de processar símbolos gráficos'},
    {'name': 'dismenorréia', 'description': 'Dor associada à menstruação'},
    {'name': 'dismetria', 'description': 'incapacidade controlar a distância, a força e a velocidade de uma ação muscular'},
    {'name': 'dispareunia', 'description': 'dor durante a relação sexual'},
    {'name': 'dispepsia', 'description': 'É um conjunto de sinais relacionados ao trato gastro intestinal com odor, queimação ou desconforto na região superior do abdomen'},
    {'name': 'dispnéia paroxística', 'description': 'Dificuldade da respiração que surge em crises, comumente à noite quando o paciente deita. Comumente conhecida como dispnéia paroxística noturna'},
    {'name': 'dispnéia', 'description': 'Dificuldade para respirar, sensação subjetiva de falta de ar ao nível de trato respiratório inferior'},
    {'name': 'disquesia', 'description': 'evacuação dolorosa'},
    {'name': 'distaxia', 'description': 'Dificuldade na coordenação de movimentos musculares voluntaries ou de equilíbrio'},
    {'name': 'distonia', 'description': 'Movimento ou postura anormal mantida, devido à alteração do tônus'},
    {'name': 'disúria', 'description': 'Micção difícil ou dolorosa'},
    {'name': 'diverticulite', 'description': 'Inflamação aguda da parede de um divertículo do cólon'},
    {'name': 'divertículo', 'description': 'Eventração de parte da mucosa do colon através de uma área enfraquecida da parede intestinal'},
    {'name': 'edema', 'description': 'Acúmulo anormal de liquido localizado nos espaços intercelulares dos tecidos ou em diferentes cavidades corpóreas'},
    {'name': 'efélides', 'description': 'São manchas ou máculas causadas pelo aumento de melanina na pele e estimuladas pela exposição ao sol. Popularmente chamadas de sardas'},
    {'name': 'embolia', 'description': 'Presença de uma substância sólida, líquida ou gasosa no circuito arterial com a consequente obstrução do fluxo'},
    {'name': 'êmese', 'description': 'vômito'},
    {'name': 'encoprese', 'description': 'Emissão involuntária de fezes, após a idade na qual o controle dos esfíncteres já deveria existir'},
    {'name': 'enema', 'description': 'Inserção de substâncias líquidas ou semilíquidas através do esfíncter anal, para induzir a defecação ou administrar medicamentos'},
    {'name': 'enfisema', 'description': 'condição patológica caracterizada por destruição das paredes dos alvéolos pulmonares'},
    {'name': 'enoftalmia', 'description': 'Retração do globo ocular, posição profunda do globo ocular na órbita'},
    {'name': 'enterorragia', 'description': 'Hemorragia intestinal com eliminação de sangue vivo pelo ânus'},
    {'name': 'enurese', 'description': 'Emissão involuntária de urina durante a noite'},
    {'name': 'epididimite', 'description': 'inflamação do epidídimo'},
    {'name': 'epífora', 'description': 'lacrimejamento excessivo'},
    {'name': 'episiotomia', 'description': 'Incisão ao nível do assoalho perineal, visando ampliar o canal do parto, facilitando o desprendimento fetal'},
    {'name': 'epispádia', 'description': 'Abertura da uretra em qualquer região da face dorsal da haste peniana'},
    {'name': 'epistaxe', 'description': 'Hemorragia de origem nasal'},
    {'name': 'epúlide', 'description': 'um nódulo não sensível e fibroso da gengiva, que emerge entre os dentes; uma resposta inflamatória à lesão ou hemorragia'},
    {'name': 'equimose', 'description': 'Mancha amarronada/acastanhada, resultante do extravasamento de sangue no tecido subcutâneo resultado de uma ruptura capila'},
    {'name': 'erisipela', 'description': 'Infecção cutânea que acomete derme e tecido subcutâneo, produzida por estreptococus'},
    {'name': 'eritema', 'description': 'Também denominado de rubor, consiste de um sinal clinico caracterizado por uma coloração avermelhada ocasionada por vasodilatação vascular'},
    {'name': 'eritrodermia', 'description': 'Eritema ou ruborização generalizada em pele'},
    {'name': 'eructação', 'description': 'Expulsão súbita, por vezes ruidosa, de gases pela boca. popularmente denominado arroto. Tem como causa principal a aerofagia'},
    {'name': 'escama', 'description': 'flocos compactados e ressecados de pele, secos ou gordurosos, prateados ou brancos, pele descolamento do excesso de células queratinizadas mortas'},
    {'name': 'esclerodermia', 'description': 'é um distúrbio crônico do tecido conjuntivo associado com a diminuição do turgor cutâneo, isto é, literalmente um  enrijecimento da pele'},
    {'name': 'esclerose múltipla' , 'description': 'doença em que o sistema imunológico destroi a cobertura protetora dos nervos'},
    {'name': 'escoriação', 'description': 'abrasão autoinfligida, superficial, às vezes em crosta, escarificações pela coceira excessiva'},
    {'name': 'escotoma', 'description': 'É uma região do campo visual que apresenta perda total ou parcial da acuidade visual, cerceada por área de visão normal'},
    {'name': 'esteatorréia', 'description': 'Presença de quantidade anormal e excessiva de gorduras nas fezes'},
    {'name': 'estomatite', 'description': 'inflamação da boca'},
    {'name': 'estridor', 'description': 'Ruído respiratório áspero, de tonalidade alta, ocorre por obstrução das vias aéreas altas'},
    {'name': 'exantema', 'description': 'erupção eritematosa generalizada e aguda, de curta duração'},
    {'name': 'exoftalmia', 'description': 'projeção do globo ocular para frente'},
    {'name': 'exsulceração', 'description': 'Processo patológico de formação de uma úlcera'},
    {'name': 'fasciculação', 'description': 'São contrações irregulares e não rítmicas de fascículos musculares, mesmo no estado de repouso. Essa condição desaparece com o a movimentação voluntária da musculatura'},
    {'name': 'fenômeno de Raynaud' , 'description': 'É uma condição na qual ocorre um exagero na resposta à temperatura fria. são afecções nas quais as arteríolas, geralmente dos dedos das mãos e dos pés, sofrem um espasmo e, em consequência, a pele torna-se pálida ou com manchas vermelhas e, posteriormente, azuis'},
    {'name': 'fimose', 'description': 'Condição na qual é impossível retrair o prepúcio sobre a glande, de forma a exteriorizá-la'},
    {'name': 'fissura', 'description': 'ruptura linear com margens abruptas, estendendo até derme, seca ou úmida'},
    {'name': 'flatulência', 'description': 'Corresponde ao acúmulo anormal de gases no estômago e/ou intestinos'},
    {'name': 'flebite', 'description': 'São inflamações que ocorrem em veias'},
    {'name': 'flictena', 'description': 'cavidade elevada contendo líquido maior de 1 cm'},
    {'name': 'foliculite', 'description': 'infecção superficial dos folículos pilosos'},
    {'name': 'fonofobia', 'description': 'Intolerância a ruídos ou sons'},
    {'name': 'fotofobia', 'description': 'Intolerância à luz'},
    {'name': 'frêmito', 'description': 'Sensação vibratória que pode ser percebida ao exame de palpação do tórax de um indivíduo no momento em que ele fala ou no momento em que respira'},
    {'name': 'frigidez', 'description': 'Insensibilidade sexual, anafrodisia'},
    {'name': 'galactorréia', 'description': 'Secreção leitosa por via mamária de forma anormal e fora do período de amamentação'},
    {'name': 'gangrena', 'description': 'Condição de morte celular/tecidual resultado de em consequência de aporte sanguíneo insuficiente e da ação de agentes externos sobre o tecido necrosado'},
    {'name': 'gastrite', 'description': 'Inflamação aguda ou crônica da mucosa estomacal'},
    {'name': 'gengivite', 'description': 'Inflamação na gengiva, sem comprometimento ósseo adjacente'},
    {'name': 'genuvalgo', 'description': 'joelhos para dentro'},
    {'name': 'genuvaro', 'description': 'pernas arqueadas'},
    {'name': 'ginecomastia', 'description': 'Inchaço do tecido mamário masculino causado por um desequilíbrio hormonal.'},
    {'name': 'glaucoma', 'description': 'Aumento da pressão intraocular'},
    {'name': 'glicosúria', 'description': 'Presença de glicose na urina'},
    {'name': 'goma', 'description': 'Lesão cuja característica apresenta-se como nódulo ou tumor que se liquefaz na porção central e que pode se ulcerar, eliminando substância necrótica. Comum em lesões de sífilis'},
    {'name': 'halitose', 'description': 'Presença de odor desagradável proveniente da cavidade oral'},
    {'name': 'halo senil' , 'description': 'Também denominado de arco senil ou gerontoxo. Corresponde a formação de um arco ou anel opaco-esbranquiçado opacidade perifericamente a córnea. Sua gênese pode estar associada ao acúmulo de colesterol, fosfolipídios e gorduras neutras; ocorre em pacientes idosos ou em jovens com história de hipercolesterolemia e xantomatose'},
    {'name': 'hematêmese', 'description': 'Eliminação de sangue por meio de vômito proveniente do tubo digestivo'},
    {'name': 'hematoma', 'description': 'Tumefação bem definida que ocorre devido a Coleção sanguínea proveniente de rompimento de vasos sanguíneos'},
    {'name': 'hematoquezia', 'description': 'É um termo médico utilizado para designar a presença de sangue com cor vermelha viva misturado as fezes. A hematoquezia está geralmente associada a uma hemorragia intestinal'},
    {'name': 'hematúria', 'description': 'É a presença de sangue na urina'},
    {'name': 'hemiplegia', 'description': 'Paralisia de uma área que afeta metade do corpo'},
    {'name': 'hemoflictema', 'description': 'Vesícula com conteúdo sanguinolento no seu interior'},
    {'name': 'hemoptise', 'description': 'Expulsão ou expectoração sanguínea ou sanguinolenta por meio da tosse, proveniente de hemorragia na árvore respiratória'},
    {'name': 'hemorragia', 'description': 'Extravasamento de sangue do sistema cardiovascular para outra topografia anatômica ou para a porção extracorpórea'},
    {'name': 'hepatite', 'description': 'Inflamação do fígado'},
    {'name': 'hifema', 'description': 'sangue na câmara anterior ocular'},
    {'name': 'hiperalgesia', 'description': 'aumento da sensação de dor. Hiperestesia: aumento da sensibilidade tátil'},
    {'name': 'hipertricose', 'description': 'Aumento do crescimento de pelos, localizada a uma topografia especifica ou generalizada, de caráter genético ou adquirido, que surge comumente em locais normalmente providos de pelos'},
    {'name': 'hiperventilação', 'description': 'aumento na frequência e na profundidade ventilatórias'},
    {'name': 'hipoacusia', 'description': 'Diminuição da acuidade auditiva'},
    {'name': 'hipoalgesia', 'description': 'diminuição da sensação de dor'},
    {'name': 'hipoestesia', 'description': 'diminuição da sensibilidade tátil'},
    {'name': 'hipópio', 'description': 'material purulento na câmara anterior'},
    {'name': 'hiposmia', 'description': 'diminuição do olfato'},
    {'name': 'hipospádia', 'description': 'o óstio da uretra se abre na superfície ventral da glande, corpo ou na junção penoescrotal'},
    {'name': 'hipostadia', 'description': 'Defeito congênito no pênis, onde o meato uretral abre-se ventralmente em qualquer ponto ao longo da haste peniana ou mesmo no períneo'},
    {'name': 'hipotricose', 'description': 'Ausência de pelos ou cabelos em topografia anatômica em que comumente deveriam aparecer'},
    {'name': 'hipoventilação', 'description': 'padrão ventilatório superficial e irregular'},
    {'name': 'hirsutismo', 'description': 'É o desenvolvimento na mulher de uma pilosidade excessiva e de feitio masculino em locais normalmente desprovidos de pelos'},
    {'name': 'histerectomia', 'description': 'É a remoção cirúrgica do útero, que também pode incluir a retirada das trompas adjacentes e do ovário'},
    {'name': 'hordéolo', 'description': 'Corresponde ao terçol. É uma infecção estafilocócica localizada na raiz dos folículos, na borda das pálpebras'},
    {'name': 'icterícia', 'description': 'cor amarelada da pele que indica aumento dos níveis de bilirrubina no sangue'},
    {'name': 'ictiose', 'description': 'Condição hereditária, onde a pele de um indivíduo apresenta forma semelhante a escamas de peixe. Ocorre principalmente em Síndrome de Zunich'},
    {'name': 'ileite', 'description': 'Inflamação do íleo',},
    {'name': 'incontinência', 'description': 'Perda da capacidade de controlar os esfíncteres anal ou vesical'},
    {'name': 'infarto', 'description': 'Morte de um tecido ou mesmo de um órgão por irrigação sanguínea insuficiente ou inadequada'},
    {'name': 'iridociclite', 'description': 'infecção de um dos anexos da vista'},
    {'name': 'irite', 'description': 'inflamação da íris'},
    {'name': 'lagoftalmia', 'description': 'É uma condição que impede a pessoa de fechar completamente as suas pálpebras'},
    {'name': 'leucocitúria', 'description': 'Presença de leucócitos na urina'},
    {'name': 'leucoderma', 'description': 'Termo para designar um paciente caucasiano'},
    {'name': 'leucoma', 'description': 'É a opacidade corneana. A córnea cursa com aspecto branco em toda sua extensão ou em parte.'},
    {'name': 'leuconíquia', 'description': 'também conhecido por linhas de Muehrcke. Presença de linhas brancas transversais nas unhas'},
    {'name': 'leucoplasia', 'description': 'Termo clínico usado para designar uma lesão de matiz esbranquiçada em mucosas'},
    {'name': 'leucorreia', 'description': 'Corrimento de coloração esbranquiçada através da vagina ou uretra'},
    {'name': 'leucotricose', 'description': 'Embranquecimento dos cabelos devido à falta de formação de melanina pelos melanócitos da matriz do pelo. Pode ser congênita, causando o albinismo, ou adquirida causando a poliose'},
    {'name': 'leucotríquia anular' , 'description': 'distrofia congênita rara, na qual os cabelos apresentam áreas claras e escuras de forma alternadas'},
    {'name': 'linfadenite', 'description': 'Inflamação dos gânglios linfáticos. Condição que comumente leva a linfadenomegalia'},
    {'name': 'linfadenomegalia', 'description': 'Aumento de linfonodos. Sinônimo de adenomegalia'},
    {'name': 'linfadenopatia', 'description': 'aumento de volume dos linfonodos, maior que 1 centimetro por infecção, alergia ou neoplasia'},
    {'name': 'lipotímia', 'description': 'Desfalecimento, desmaio fugaz, sem que ocorra perda de consciência'},
    {'name': 'lombalgia', 'description': 'Dor na região lombar'},
    {'name': 'macrocefalia', 'description': 'cabeça anormalmente grande'},
    {'name': 'mácula', 'description': 'Pequena mancha cutânea plana, sem elevação, com coloração distinta do tecido que a circunda'},
    {'name': 'madarose', 'description': 'É uma condição que resulta na perda dos cílios, por vezes, as sobrancelhas. Corresponde a um estigma da hanseníase'},
    {'name': 'marasmo', 'description': 'É uma forma de desnutrição que causa perda do tecido muscular e subcutâneo'},
    {'name': 'mastalgia', 'description': 'dor nas mamas',},
    {'name': 'mastite', 'description': 'inflamação das mamas'},
    {'name': 'mecôneo', 'description': 'Substância pastosa de cor esverdeada, que é coletada no intestino do feto e constitui as primeiras evacuações dos recém-nascidos. Quando presentes dentro da barriga, pode indicar sofrimento fetal'},
    {'name': 'melanoderma', 'description': 'Termo para designar um paciente afrodescendente'},
    {'name': 'melena', 'description': 'Evacuação de fezes de cor negra, que indica presença de sangue digerido no conteúdo fecal. Fezes moles e pastosas, em aspecto de borra de café e com odor bastante fétido'},
    {'name': 'melenêmese', 'description': 'Vômito em forma de borra de café. Ocorre quando o sangue esteve em contato com o ácido gástrico por um período de tempo'},
    {'name': 'menarca', 'description': 'Corresponde a primeira menstruação de uma mulher, geralmente por volta dos 12-15 anos'},
    {'name': 'menopausa', 'description': 'Período da vida da mulher em que cessa a menstruação'},
    {'name': 'metástase', 'description':  'Presença de tecido tumoral ou neoplásico, localizada em um lugar distante do sítio de origem, por dissiminação hematogênica ou linfática'},
    {'name': 'meteorismo', 'description': 'Intumescência abdominal resultado do acúmulo de gases no estômago e alças intestinais'},
    {'name': 'método não invasivo' , 'description': 'Procedimentos em que não envolvem instrumentos que rompem a pele ou que penetram fisicamente no organismo'},
    {'name': 'metrorragia', 'description': 'É o sangramento uterino irregular, fora do período menstrual'},
    {'name': 'mialgia', 'description': 'dor muscular'},
    {'name': 'microcefalia', 'description': 'cabeça anormalmente pequena'},
    {'name': 'microtia', 'description': 'orelhas menores que 4 cm verticalmente'},
    {'name': 'midríase', 'description': 'É a dilatação da pupila em função da contração do músculo dilatado da pupila'},
    {'name': 'mioclonia', 'description': 'Contração muscular involuntária e súbita'},
    {'name': 'miose', 'description': 'Contração da pupila. Diminuição do diâmetro pupilar'},
    {'name': 'multípara', 'description': 'mulher que deu a luz a mais de um filho'},
    {'name': 'narcose', 'description': 'é o nome dado à alteração do estado de consciência devido à intoxicação por determinadas substâncias, como narcóticos'},
    {'name': 'nevo', 'description': 'São pequenas manchas ou elevações de coloração acastanhada ou enegrecida na pele e que aparecem nas primeiras décadas de vida em quase todas as pessoas'},
    {'name': 'nictúria', 'description': 'maior volume urinário durante a noite do que durante o dia noturno sobre o diurno'},
    {'name': 'nistagmo', 'description': 'Tremores rítmicos, involuntários e bilaterais dos globos oculares no sentido horizontal, vertical ou rotatório'},
    {'name': 'noctúria', 'description': 'aumento da frequência de micções à noite'},
    {'name': 'nódulo', 'description': 'Lesão sólida, elevada, apresentando diâmetro maior que 1 centímetro'},
    {'name': 'nucalgia', 'description': 'Dor na nuca'},
    {'name': 'nulípara', 'description': 'mulher que nunca deu à luz'},
    {'name': 'obstipação', 'description': 'aumento no intervalo entre as evacuações. Acompanhada de fezes ressecadas e dificuldade na eliminação das mesmas. É definida como uma alteração do hábito intestinal na qual o indivíduo fica sem evacuar por mais de 3 dias. Também conhecida como prisão de ventre'},
    {'name': 'odinofagia', 'description': 'Dor que ocorre durante o processo de deglutição'},
    {'name': 'odontalgia', 'description': 'dor de dente'},
    {'name': 'oligomenorréia', 'description': 'Menstruação irregulares com intervalos prolongados. A presença da oligomenorréia sugere disfunção ovariana'},
    {'name': 'oligúria', 'description':  'Redução importante no volume urinário diário, geralmente menor que 100 ml em adultos'},
    {'name': 'onicofagia', 'description': 'hábito de roer as unhas',},
    {'name': 'onicólise', 'description': 'Descolamento da unha do leito ungueal, a partir de sua ligação distal ou lateral'},
    {'name': 'onicomalácia', 'description': 'Unha de consistência amolecida e friável. Sugere sinal de doenças sistêmicas'},
    {'name': 'ooforite', 'description': 'Inflamação do ovário'},
    {'name': 'orquite', 'description': 'Processo inflamatório do testículo',},
    {'name': 'ortopnéia', 'description': 'Dificuldade para respirar quando o paciente está deitado. Melhora quando o paciente se senta, mantendo o tronco ligeiramente fletido'},
    {'name': 'osteomalácia', 'description': 'Paciente apresenta amolecimento e curvatura gradual dos ossos com sintomatologia dolorosa de intensidade variável. Resultado da calcificação deficiente em virtude da deficiência de vitamina D. É também conhecida como Raquitismo do adulto'},
    {'name': 'otalgia', 'description': 'Dor de ouvido'},
    {'name': 'otorragia', 'description': 'Sangramento expelido pelo ouvido'},
    {'name': 'otorréia', 'description': 'saída de secreção do ouvido'},
    {'name': 'palpitação', 'description': 'Percepção subjetica e incômoda de batimento acelerado ou irregular do coração'},
    {'name': 'pápula', 'description': 'lesão sólida, elevada, apresentando até 1 cm de diâmetro'},
    {'name': 'parafimose', 'description': 'o prepúcio é retraído e fixo'},
    {'name': 'paralisia de Bell' , 'description': 'Acometimento que ocorre no nervo facial que leva à fraqueza repentina ou à paralisia dos músculos de um dos lados da face'},
    {'name': 'paraplegia', 'description': 'Paralisia completa de dois segmentos simétricos do corpo, geralmente dos membros inferiores'},
    {'name': 'paresia', 'description': 'Perda parcial da motricidade, diminuição da força muscular'},
    {'name': 'parestesia', 'description': 'Aparecimento de sensação anormal e mal definidas, sem prévia estimulação. Dormência e formigamento são os representantes mais significativos da parestesia'},
    {'name': 'paroníquia', 'description': 'É uma infecção da pele que situa-se ao redor das unhas dos dedos das mãos ou dos pés'},
    {'name': 'pectorilóquia', 'description': 'Palavra pode ser ouvida com nitidez durante o processo de ausculta pulmonar',},
    {'name': 'pênfigo', 'description': 'Denominação geral a um grupo de doenças autoimunes, pouco frequentes, consistindo em dermatoses crônicas, recidivastes e algumas vezes fatais. São caracterizadas clinicamente pelo aparecimento de sucessivos grupos de vesículas e bolhas, inicialmente na mucosa bucal ou orofaríngea e, depois, na pele aparentemente sadia. As bolhas se rompem deixando uma zona erodida, posteriormente recoberta por crostas. A epiderme descola-se facilmente do plano subjacente'},
    {'name': 'petéquias', 'description': 'pequenas hemorragias puntiformes de 1 a 3 mm, arredondadas e discretas, com cor púrpura ou marrom',},
    {'name': 'pinguécula', 'description': 'nódulos elevados e amarelados que surgem a partir de um espessamento da conjuntiva bulbar pela exposição prolongada ao sol, vento e poeira'},
    {'name': 'pirexia', 'description': 'aumento da temperatura corporal acima dos níveis normais para o indivíduo'},
    {'name': 'pirose', 'description': 'Sensação de calor ou queimação no estômago. Conhecida como azia'},
    {'name': 'piúria', 'description': 'Presença de pus na urina'},
    {'name': 'plegia', 'description': 'Perda de força muscular ou paralisia'},
    {'name': 'pletória', 'description': 'Aumento local ou geral da massa sanguínea. Quando local pode ser denominado de congestão.'},
    {'name': 'polaciúria', 'description': 'Aumento da frequência urinária, sem relação com o volume de urina excretado'},
    {'name': 'polidactilia', 'description': 'presença de dígitos extras'},
    {'name': 'polidipsia', 'description': 'Termo que refere a sede excessiva'},
    {'name': 'polifagia', 'description': 'Fome excessiva'},
    {'name': 'poliúria', 'description': 'Aumento no volume normal de urina excretado nas 24 horas'},
    {'name': 'presbiacusia', 'description': 'é uma perda sensorioneural gradual causada pela degeneração na orelha interna que progride lentamente após a quinta década'},
    {'name': 'presbiopia', 'description': 'diminuição do poder de acomodação visual com o envelhecimento'},
    {'name': 'priapismo', 'description': 'Ereção prolongada, não associada com estimulação sexual e geralmente dolorosa'},
    {'name': 'proctite', 'description': 'Inflamação da mucosa do reto'},
    {'name': 'pródromo', 'description': 'Manifestação clínica ou sintomática que antecede uma doença'},
    {'name': 'proptose', 'description': 'Deslocamento de um órgão para frente'},
    {'name': 'pterígio', 'description': 'Tecido fibrovascular recoberto pela conjuntiva ocular, de forma triangular e geralmente localizado no canto interno do olho'},
    {'name': 'ptose palpebral' , 'description': 'Queda da pálpebra associada a lesão do nervo oculomotor'},
    {'name': 'pústula', 'description': 'Vesícula de conteúdo purulento'},
    {'name': 'puxo', 'description': 'Contração espasmódica do reto que precede as evacuações'},
    {'name': 'queilite', 'description': 'rachadura nos cantos da boca',},
    {'name': 'queloide', 'description': 'é uma cicatriz hipertrófica onde o nível da pele resultante está elevado pelo excesso de tecido cicatricial, que invade além do local original da lesão', 'queratose': 'são áreas elevadas e espessadas de pigmentação que aparecem com crostas, camadas e verrugas'},
    {'name': 'rash', 'description': 'Erupção de coloração avermelhada, eritematosa em pele como resultado de uma reação alérgica ou infecção. Sinonimo de exantema'},
    {'name': 'regurgitação', 'description': 'Retorno à boca ou garganta do alimento recém ingerido sem esforço de vômito, ocasionado por refluxo intenso'},
    {'name': 'ressecção', 'description': 'Extirpação cirúrgica parcial ou total de um órgão'},
    {'name': 'rinite', 'description': 'Inflamação do nariz'},
    {'name': 'rinorréia', 'description': 'Secreção nasal'},
    {'name': 'salicismo', 'description': 'Intoxicação por ácido salicílico, aspirina'},
    {'name': 'sepse', 'description': 'antiga septicemia. Disseminação de bactérias patogênicas partir de um foco de infecção através da circulação sistêmica'},
    {'name': 'sialorréia', 'description': 'Aumento da secreção de saliva'},
    {'name': 'sialosquise', 'description': 'Diminuição da secreção de saliva',},
    {'name': 'sinal patognomônico' , 'description': 'Manifestação específica de uma entidade patológica'},
    {'name': 'síncope', 'description': 'perda súbita da consciência, geralmente acompanhada de perda do tônus postural'},
    {'name': 'sindactilia', 'description': 'presença de dedos ligados',},
    {'name': 'síndrome', 'description': 'Conjunto de sinais e sintomas de mesma marcha evolutiva, porém de causas diversas, que caracterizam um estado mórbido e que se repete na população'},
    {'name': 'sintoma', 'description': 'Manifestação subjetiva de uma doença. Também é uma percepção normal que uma pessoa tem de seu próprio corpo'},
    {'name': 'sinusite', 'description': 'inflamação dos seios paranasais'},
    {'name': 'supuração', 'description': 'Presença de secreção purulenta'},
    {'name': 'taquicardia', 'description': 'Aceleração dos batimentos cardíacos, comumente considerado acima de 100 batimentos por minuto'},
    {'name': 'taquipnéia', 'description': 'Aumento da frequência respiratória'},
    {'name': 'telangiectasia', 'description': 'vasos sanguíneos dilatados e permanentemente aumentados que são visíveis na superfície da pele',},
    {'name': 'tenesmo', 'description': 'Espasmo doloroso do esfíncter anal ou vesical com desejo urgente de defecar ou urinar. Há eliminação de quantidade mínima de fezes ou urina'},
    {'name': 'tique', 'description': 'Movimento repetido irregular espasmódico'},
    {'name': 'trepanação', 'description': 'É uma intervenção cirúrgica, em que um buraco (fenestra) é aberto no crânio humano'},
    {'name': 'tricotilomania', 'description': 'perda traumática autoinduzida do cabelo, usualmente como resultado do retorcimento ou arrancamento compulsivo'},
    {'name': 'tricotomia', 'description': 'é um procedimento pré-cirúrgico que tem como objetivo remover os pelos da região a ser cortada para facilitar a visualização da região pelo médico e evitar possíveis infecções após a cirurgia e, consequentemente, complicações para o paciente'},
    {'name': 'tumor', 'description': 'Lesão sólida, elevada, com mais de 3 cm de diâmetro'},
    {'name': 'úlcera', 'description': 'perda de resvestimento epitelial deixando o tecido conjuntivo ou derme desnuda'},
    {'name': 'unhas de Lindsay', 'description': 'Unhas apresentando metade proximal de cor branca, 20-50% distal vermelho. Ocorre na insuficiência renal'},
    {'name': 'unhas hipocráticas', 'description': 'Unhas recurvadas, em padrão de vidro de relógio, com baqueteamento digital'},
    {'name': 'uretrite', 'description': 'inflamação da uretra',},
    {'name': 'urtica', 'description': 'Pápula eritêmato-edematosa, de duração efêmera que tem frequentemente a borda irregular com aspecto de irregular. Pode coalescer e formar placa eritematosa'},
    {'name': 'urticária', 'description': 'pápulas que coalescem para forma uma extensa reação, intensamente pruriginosa'},
    {'name': 'vaginismo', 'description': 'Contração involuntária da vagina'},
    {'name': 'vaginite', 'description': 'Inflamação da mucosa que reveste a vagina'},
    {'name': 'vegetações', 'description': 'Projeções sólidas, digitiformes, moles, por vezes sangrantes e de tamanhos variáveis'},
    {'name': 'verruga', 'description': 'Vegetação de superfície queratótica, de aspecto irregular'},
    {'name': 'vertigem', 'description': 'Sensação de rotação do organismo em relação ao ambiente ou do ambiente em relação ao organismo por alteração do sistema laberíntico ou cerebelar'},
    {'name': 'vesícula', 'description': 'Coleção líquida, elevada, com diâmetro de até 1 cm'},
    {'name': 'xantelasma', 'description': 'manchas ou placas amarelas que surge na região das pálpebras, provocada pelo depósito de lipídeos'},
    {'name': 'xantoderma', 'description': 'Termo para designar paciente nipônico, pele de cor amarela'},
    {'name': 'xantomatose', 'description': 'Acúmulo de excesso de lipídios no organismo por alteração metabólica ou formação de tumores'},
    {'name': 'xeroftalmia', 'description': 'Perda da secreção lacrimal e caracterização de ressecamento excessivo das mucosas que revestem o olho'}, 
    {'name': 'xerostomia', 'description': 'Ressecamento da boca em resultado pela secreção insuficiente ou ausente das glândulas salivares'}
];
