

// colocar as doencas e definicoes.
//e acionar diretamente no index
//colocar a id no build

module.exports = {
'abscesso': 'constitui uma coleção de pus ou material purulento, comumente associado a uma infecção bacteriana',
'abulia': 'perturbação ou Alteração fisiopatológica caracterizada por diminuição ou supressão da vontade',
'acalásia': 'compreende a ausência de relaxamento dos esfíncteres. Comumente decorrente de distúrbio nervoso ou por causa desconhecida',
'acrocianose': 'distúrbio circulatório que manifesta-se em extremidades tornando-as frias e de coloração azulada. Ocorre principalmente em mãos, e menos comumente os pés, algumas manifestações de acrocianose estão associadas ao fenômeno de Raynaud',
'acrocórdons': 'também chamados de pólipos cutâneos, são crescimentos exagerados da pele normal que formam uma haste e são parecidos com pólipos',
'acromegalia': 'é um distúrbio representado pelo aumento desproporcional dos membros e face, associados a hiperfunção da hipófise',
'adenite' : 'inflamação ou ingurgitamento de uma glândula ou gânglio linfático',
'adenomegalia': ' hipertrofia de um gânglio linfático',
'adipsia': 'falta de sede',
'aerofagia': 'ato de deglutir ar Acomete algumas pessoas, especialmente as que sofrem de dispepsia ou de certos estados ansiosos, neuróticos ou mesmo em situações que levem um indivíduo à uma agitação física e psíquica',
'afagia': 'impossibilidade de deglutir',
'afasia': 'sintoma neurológico revelado por perda ou incapacidade de expressar ou interpretar a linguagem falada ou escrita',
'afebril': 'sem febre',
'aférese': 'remoção do sangue do próprio paciente',
'agalactia': 'ausência de leite nas mamas depois do parto; agalactose',
'ageusia': 'ausência ou redução do sentido do paladar',
'aglossia': 'ausência congênita da língua',
'agnosia': 'é uma perturbação que se caracteriza pelo fato de a pessoa poder ver e sentir os objetos',
'agorafobia': 'distúrbio caracterizado pela sensação de medo de estar só em espaço aberto',
'agrafia': 'é uma incapacidade para traduzir as idéias por escrito, apesar de não haver nenhum comprometimento psicomotor, da fala ou da compreensão',
'alodinia': 'envolve uma mudança no sentido da dor, da qualidade de uma sensação, seja do tipo que for',
'alopécia': 'é a redução parcial ou total de pelos ou cabelos em uma determinada área de pele',
'amaurose': 'é a perda total da visão',
'amenorreia': 'ausência de mestruação',
'anacusia': 'total perda da capacidade auditiva',
'anafrodisia': 'corresponde a falta de desejo sexual. Frigidez',
'analgesia': 'perda ou ausência de sensibilidade dolorosa',
'anasarca': 'acúmulo generalizado de líquidos entre os tecidos ou edema generalizado',
'anastomose': 'união entre estruturas tubulares',
'anciloglossia': 'encurtamento do frênulo da língua',
'anestesia': 'ausência de sensibilidade tátil',
'aneurisma': 'alargamento de forma anormal da luz de um vaso sanguíneo',
'angina': 'termo médico utilizado para se referir à sensação opressiva que decorre da falta de oxigênaçã do músculo cardíaco',
'anisocoria': 'tamnho desigual ds pupilas',
'anorexia': 'distúrbio alimentar que leva a pessoa a ter uma visão distorcida do seu corpo',
'anosmia': 'diminuição ouperda total do olfato',
'anquiloglossia': 'distúrbio de desenvolvimento revelado pela presença de freio lingual curto, leva ao fenômeno conhecido como língua presa',
'anquilose': 'imobilidade de uma articulação',
'anúria': 'ausência de secreção urinária',
'apnéia do sono': 'é um distúrbio do sono potencialmente grave em que a respiração cessa e começa repetidamente',
'apneia': 'supressão momentânea da respiração',
'apraxia': 'é um distúrbio neurológico revelado pela incapacidade de executar movimentos coordenados',
'artralgia': 'dor em articulações',
'artrite': 'inflamação que acomete articulações',
'artrose': 'condição degenerativa representada pelo adelgaçamento ou destruição da cartilagem articular e deformação das superfície óssea de uma ou mais articulações',
'ascite': 'acúmulo anormal de líquidos dentro da cavidade peritoneal',
'astenia': 'ausência ou perda de força muscular',
'ataxia': 'falta de coordenação de movimentos musculares voluntaries ou mesmo de equilíbrio',
'atetose': 'consequência de lesões centrais, caracterizada por apresentar movimentos irregulares e arrítmicos de mãos, pés associado a distensões e contrações dos dedos',
'atresia': 'estreitamento ou oclusão de qualquer canal do corpo',
'atrofia': 'perda de massa muscular',
'baqueamento digital': 'conhecido também por unhas em Vidro de relógio ou hipocráticas. Ocorre quando o ângulo do leito ungueal é maior que 180 graus. Comun em doenças que comprometem a circulação pulmonar',
'blefarite': 'inflamação das pálpebras',
'bócio': 'aumento de volume crônico da tireoide que ocorre em algumas regiões do mundo com dieta pobre em iodo',
'bolha': 'termo semiológico que se refere à uma lesão elevada, maior que 1 cm de diâmetro e que apresenta acúmulo de liquido de aspecto claro ou citrino. Ocorre prevalentemente entre as camadas superficiais da epiderme ou mucosa',
'bradicardia': 'diminuição da frequência cardíaca a menos de 60 batimentos por minuto',
'bradicinesia': 'termo médico que define a lentidão anormal dos movimentos',
'bradipneia': 'respiração lenta. Frequência ventilatória diminuída, abaixo de 8 inspirações por minuto',
'bulimia': 'é a ingesta compulsiva de alimentos, comumente seguida de indução de vômitos',
'cacifo': 'sinal clinico avaliado por meio de pressão digital sobre um edema de pele. Considera-se cacifo positivo em áreas onde a compressão não se desfaz imediatamente após a remoção da pressão digital',
'cacofagia': 'estado mórbido em que o paciente apresenta perversão do apetite, fazendo-o ingerir substâncias consideradas repugnantes, como exemplo fezes',
'cacosmia': 'indivíduo que aprecia ou sente atração por cheiros desagradáveis',
'calázio': 'condição inflamatória caracterizada por pequeno nódulo localizado em região inferior ou superior das pálpebras causado pelo bloqueio dos orifícios das glândulas palpebrais',
'calvície': 'também denominada de alopécia androgênica. É uma afecção, comum no homem e rara na mulher, representada por perda de cabelos',
'canície': 'despigmentação capilar que surge fisiologicamente a partir da terceira década de vida',
'caquexia': 'emagrecimento extremo com comprometimento franco do estado geral e incapacidade de desempenhar atividades mínimas',
'catatonia': 'quadro clinico onde ocorre uma perturbação da iniciativa e comportamento motor, bem como do grau de tensão muscular. É comum em transtornos psiquiátricos',
'cefaleia': 'dor de cabeça',
'celulite': 'inflamação de tecido conjuntivo subcutâneo frouxo',
'ceratite': 'inflamação na córnea',
'ceratocone': 'é uma condição patológica que afeta o formato e a espessura da córnea, como resultado, o paciente apresenta percepção distorcida de imagens',
'cervicalgia': 'dor localizada na região cervical, isto é na parte posterior do pescoço ou nuca',
'cervicite':  'inflamação localizada no colo uterino',
'choque anafilático': 'constitui uma reação alérgica grave, resultando em diminuição da pressão arterial, taquicardia, acompanhado ou não de edema de glote',
'choque séptico': 'é o termo médico utilizado para designar a falência circulatório aguda por causa infecciosa',
'choque': 'sofrimento celular fruto da falta de irrigação sanguínea',
'cianose': 'sinal onde o paciente apresenta cor azulada ou arroxeada da pele e das mucosas, decorrente da diminuição da oxigenação tecidual',
'cistite': 'inflamação da bexiga',
'cisto': 'cavidade encapsulada cheia de líquido na derme ou camada subcutânea, elevando a pele sob tensão',
'claudicação': 'é um termo médico para designar distúrbio de marcha devido a diferenças anatômicas ou funcionais entre os membros inferiores',
'cloasma': 'é uma área acastanhada irregular de hiper-pigmentação na face',
'clônus': 'série de contrações involuntárias devido a um estiramento súbito do músculo',
'coiloníquia': 'unha em forma de colher',
'coitarca': 'idade da primeira atividade sexual',
'colêmese': 'vômito com bile',
'colestase': 'iminuição ou interrupção do fluxo da bilis como resultado de retenção do conteúdo biliar no parênquima hepático.',
'colite': 'inflamação do cólon',
'conjuntivite': 'inflamação da conjuntiva',
'constipação': 'afecção produzida por alteração de transito intestinal, gerando retenção de fezes ou dificuldade de sua evacuação',
'coriza': 'corrimento de secreção nasal',
'criptoquirdia': 'testículos não descidos',
'dacriocistite':  'inflamação do saco nasolacrimal',
'delírio': 'Alteração aguda da consciência ou da lucidez, fruto de um distúrbio orgânica',
'derrame pleural': 'acúmulo de líquido no espaço pleural do tórax',
'derrame': 'Acúmulo anormal de liquido em qualquer cavidade ou órgão',
'diarréia': 'Tecnicamente consiste em evacuação de mais de 200 g de fezes ao dia. É uma também uma perturbação intestinal caracterizada por aumento frequência de evacuações',
'diérese': 'Segmentação de fragmentos de tecidos orgânicos normalmente unidas, de forma acidental ou cirúrgica, sem perda de substância',
'diplopia': 'Presença de visão dupla relatada pelo paciente, ocorre comumente em estrabismo',
'disacusia': 'Estado mórbido em que sons produzem distúrbio da audição, dor ou mal-estar',
'disartria': 'dificuldade na articulação da fala',
'disdiadococinesia': 'Incapacidade de realizar eficientemente movimentos rápidos e alternados. Ocorre comumente em doença cerebelar',
'disenteria': 'Diarréia com a presença de muco, pus ou sangue nas fezes e dor à evacuação',
'disfagia': 'Distúrbio em que o paciente apresenta dificuldade de deglutição',
'disfasia': 'Perturbação na compreensão ou expressão da linguagem',
'disfonia': 'Alteração ou dificuldade da produção normal da voz',
'dislalia': 'é um distúrbio da fala, caracterizado pela dificuldade em articular as palavras. Basicamente consiste na má pronúncia das palavras, seja omitindo ou acrescentando fonemas, trocando um fonema por outro ou ainda distorcendo-os ordenadamente',
'dislexia': 'Disfasia escrita ou dificuldade de leitura, apesar da visão e da articulação das palavras apresentarem-se normais. Resulta de um defeito da habilidade de processar símbolos gráficos',
'dismenorréia': 'Dor associada à menstruação',
'dismetria': 'incapacidade controlar a distância, a força e a velocidade de uma ação muscular',
'dispareunia': 'dor durante a relação sexual',
'dispepsia': 'É um conjunto de sinais relacionados ao trato gastro intestinal com odor, queimação ou desconforto na região superior do abdomen',
'dispnéia paroxística': 'Dificuldade da respiração que surge em crises, comumente à noite quando o paciente deita. Comumente conhecida como dispnéia paroxística noturna',
'dispnéia': 'Dificuldade para respirar, sensação subjetiva de falta de ar ao nível de trato respiratório inferior',
'disquesia': 'evacuação dolorosa',
'distaxia': 'Dificuldade na coordenação de movimentos musculares voluntaries ou de equilíbrio',
'distonia': 'Movimento ou postura anormal mantida, devido à alteração do tônus',
'disúria': 'Micção difícil ou dolorosa',
'diverticulite': 'Inflamação aguda da parede de um divertículo do cólon',
'divertículo': 'Eventração de parte da mucosa do colon através de uma área enfraquecida da parede intestinal',
'edema': 'Acúmulo anormal de liquido localizado nos espaços intercelulares dos tecidos ou em diferentes cavidades corpóreas',
'efélides': 'São manchas ou máculas causadas pelo aumento de melanina na pele e estimuladas pela exposição ao sol. Popularmente chamadas de sardas',
'embolia': 'Presença de uma substância sólida, líquida ou gasosa no circuito arterial com a consequente obstrução do fluxo',
'êmese': 'vômito',
'encoprese': 'Emissão involuntária de fezes, após a idade na qual o controle dos esfíncteres já deveria existir',
'enema': 'Inserção de substâncias líquidas ou semilíquidas através do esfíncter anal, para induzir a defecação ou administrar medicamentos',
'enfisema': 'condição patológica caracterizada por destruição das paredes dos alvéolos pulmonares',
'enoftalmia': 'Retração do globo ocular, posição profunda do globo ocular na órbita',
'enterorragia': 'Hemorragia intestinal com eliminação de sangue vivo pelo ânus',
'enurese': 'Emissão involuntária de urina durante a noite',
'epididimite': 'inflamação do epidídimo',
'epífora': 'lacrimejamento excessivo',
'episiotomia': 'Incisão ao nível do assoalho perineal, visando ampliar o canal do parto, facilitando o desprendimento fetal',
'epispádia': 'Abertura da uretra em qualquer região da face dorsal da haste peniana',
'epistaxe': 'Hemorragia de origem nasal',
'epúlide': 'um nódulo não sensível e fibroso da gengiva, que emerge entre os dentes; uma resposta inflamatória à lesão ou hemorragia',
'equimose': 'Mancha amarronada/acastanhada, resultante do extravasamento de sangue no tecido subcutâneo resultado de uma ruptura capila',
'erisipela': 'Infecção cutânea que acomete derme e tecido subcutâneo, produzida por estreptococus',
'eritema': 'Também denominado de rubor, consiste de um sinal clinico caracterizado por uma coloração avermelhada ocasionada por vasodilatação vascular',
'eritrodermia': 'Eritema ou ruborização generalizada em pele',
'eructação': 'Expulsão súbita, por vezes ruidosa, de gases pela boca. popularmente denominado arroto. Tem como causa principal a aerofagia',
'escama': 'flocos compactados e ressecados de pele, secos ou gordurosos, prateados ou brancos, pele descolamento do excesso de células queratinizadas mortas',
'esclerodermia': 'é um distúrbio crônico do tecido conjuntivo associado com a diminuição do turgor cutâneo, isto é, literalmente um  enrijecimento da pele',
'esclerose múltipla': 'doença em que o sistema imunológico destroi a cobertura protetora dos nervos',
'escoriação': 'abrasão autoinfligida, superficial, às vezes em crosta, escarificações pela coceira excessiva',
'escotoma': 'É uma região do campo visual que apresenta perda total ou parcial da acuidade visual, cerceada por área de visão normal',
'esteatorréia': 'Presença de quantidade anormal e excessiva de gorduras nas fezes',
'estomatite': 'inflamação da boca',
'estridor': 'Ruído respiratório áspero, de tonalidade alta, ocorre por obstrução das vias aéreas altas',
'exantema': 'erupção eritematosa generalizada e aguda, de curta duração',
'exoftalmia': 'projeção do globo ocular para frente',
'exsulceração': 'Processo patológico de formação de uma úlcera',
'fasciculação': 'São contrações irregulares e não rítmicas de fascículos musculares, mesmo no estado de repouso. Essa condição desaparece com o a movimentação voluntária da musculatura',
'fenômeno de Raynaud': 'É uma condição na qual ocorre um exagero na resposta à temperatura fria. são afecções nas quais as arteríolas, geralmente dos dedos das mãos e dos pés, sofrem um espasmo e, em consequência, a pele torna-se pálida ou com manchas vermelhas e, posteriormente, azuis',
'fimose': 'Condição na qual é impossível retrair o prepúcio sobre a glande, de forma a exteriorizá-la',
'fissura': 'ruptura linear com margens abruptas, estendendo até derme, seca ou úmida',
'flatulência': 'Corresponde ao acúmulo anormal de gases no estômago e/ou intestinos',
'flebite': 'São inflamações que ocorrem em veias',
'flictena': 'cavidade elevada contendo líquido maior de 1 cm',
'foliculite': 'infecção superficial dos folículos pilosos',
'fonofobia': 'Intolerância a ruídos ou sons',
'fotofobia': 'Intolerância à luz',
'frêmito': 'Sensação vibratória que pode ser percebida ao exame de palpação do tórax de um indivíduo no momento em que ele fala ou no momento em que respira',
'frigidez': 'Insensibilidade sexual, anafrodisia',
'galactorréia': 'Secreção leitosa por via mamária de forma anormal e fora do período de amamentação',
'gangrena': 'Condição de morte celular/tecidual resultado de em consequência de aporte sanguíneo insuficiente e da ação de agentes externos sobre o tecido necrosado',
'gastrite': 'Inflamação aguda ou crônica da mucosa estomacal',
'genuvalgo': 'joelhos para dentro',
'genuvaro': 'pernas arqueadas',
'gengivite': 'Inflamação na gengiva, sem comprometimento ósseo adjacente',
'ginecomastia': 'Inchaço do tecido mamário masculino causado por um desequilíbrio hormonal.',
'glaucoma': 'Aumento da pressão intraocular',
'glicosúria': 'Presença de glicose na urina',
'goma': 'Lesão cuja característica apresenta-se como nódulo ou tumor que se liquefaz na porção central e que pode se ulcerar, eliminando substância necrótica. Comum em lesões de sífilis',
'halitose': 'Presença de odor desagradável proveniente da cavidade oral',
'halo senil': 'Também denominado de arco senil ou gerontoxo. Corresponde a formação de um arco ou anel opaco-esbranquiçado opacidade perifericamente a córnea. Sua gênese pode estar associada ao acúmulo de colesterol, fosfolipídios e gorduras neutras; ocorre em pacientes idosos ou em jovens com história de hipercolesterolemia e xantomatose',
'hematêmese': 'Eliminação de sangue por meio de vômito proveniente do tubo digestivo',
'hematoma': 'Tumefação bem definida que ocorre devido a Coleção sanguínea proveniente de rompimento de vasos sanguíneos',
'hematoquezia': 'É um termo médico utilizado para designar a presença de sangue com cor vermelha viva misturado as fezes. A hematoquezia está geralmente associada a uma hemorragia intestinal',
'hematúria': 'É a presença de sangue na urina',
'hemiplegia': 'Paralisia de uma área que afeta metade do corpo',
'hemoflictema': 'Vesícula com conteúdo sanguinolento no seu interior',
'hemoptise': 'Expulsão ou expectoração sanguínea ou sanguinolenta por meio da tosse, proveniente de hemorragia na árvore respiratória',
'hemorragia': 'Extravasamento de sangue do sistema cardiovascular para outra topografia anatômica ou para a porção extracorpórea',
'hepatite': 'Inflamação do fígado',
'hifema': 'sangue na câmara anterior ocular',
'hiperalgesia': 'aumento da sensação de dor. Hiperestesia: aumento da sensibilidade tátil',
'hipertricose': 'Aumento do crescimento de pelos, localizada a uma topografia especifica ou generalizada, de caráter genético ou adquirido, que surge comumente em locais normalmente providos de pelos',
'hiperventilação': 'aumento na frequência e na profundidade ventilatórias',
'hipoacusia': 'Diminuição da acuidade auditiva',
'hipostadia': 'Defeito congênito no pênis, onde o meato uretral abre-se ventralmente em qualquer ponto ao longo da haste peniana ou mesmo no períneo',
 'hipoalgesia': 'diminuição da sensação de dor',
'hipoestesia': 'diminuição da sensibilidade tátil',
'hipópio': 'material purulento na câmara anterior',
'hiposmia': 'diminuição do olfato',
'hipospádia': 'o óstio da uretra se abre na superfície ventral da glande, corpo ou na junção penoescrotal',
'hipoventilação': 'padrão ventilatório superficial e irregular',
'hipotricose': 'Ausência de pelos ou cabelos em topografia anatômica em que comumente deveriam aparecer',
'hirsutismo': 'É o desenvolvimento na mulher de uma pilosidade excessiva e de feitio masculino em locais normalmente desprovidos de pelos',
'histerectomia': 'É a remoção cirúrgica do útero, que também pode incluir a retirada das trompas adjacentes e do ovário',
'hordéolo': 'Corresponde ao terçol. É uma infecção estafilocócica localizada na raiz dos folículos, na borda das pálpebras',
'Icterícia': 'cor amarelada da pele que indica aumento dos níveis de bilirrubina no sangue',
'ictiose': 'Condição hereditária, onde a pele de um indivíduo apresenta forma semelhante a escamas de peixe. Ocorre principalmente em Síndrome de Zunich',
'ileite': 'Inflamação do íleo', 
'infarto': 'Morte de um tecido ou mesmo de um órgão por irrigação sanguínea insuficiente ou inadequada',
'Incontinência': 'Perda da capacidade de controlar os esfíncteres anal ou vesical',
'iridociclite': 'infecção de um dos anexos da vista',
'irite': 'inflamação da íris',
'lagoftalmia': 'É uma condição que impede a pessoa de fechar completamente as suas pálpebras',
'leucocitúria': 'Presença de leucócitos na urina',
'leuconíquia': 'também conhecido por linhas de Muehrcke. Presença de linhas brancas transversais nas unhas',
'leucoderma': 'Termo para designar um paciente caucasiano',
'leucoma': 'É a opacidade corneana. A córnea cursa com aspecto branco em toda sua extensão ou em parte.',
'leucoplasia': 'Termo clínico usado para designar uma lesão de matiz esbranquiçada em mucosas',
'leucorreia': 'Corrimento de coloração esbranquiçada através da vagina ou uretra',
'leucotricose': 'Embranquecimento dos cabelos devido à falta de formação de melanina pelos melanócitos da matriz do pelo. Pode ser congênita, causando o albinismo, ou adquirida causando a poliose',
'leucotríquia anular': 'distrofia congênita rara, na qual os cabelos apresentam áreas claras e escuras de forma alternadas',
'linfadenopatia': 'aumento de volume dos linfonodos, maior que 1 centimetro por infecção, alergia ou neoplasia',
'linfadenite': 'Inflamação dos gânglios linfáticos. Condição que comumente leva a linfadenomegalia',
'linfadenomegalia': 'Aumento de linfonodos. Sinônimo de adenomegalia',
'lipotímia': 'Desfalecimento, desmaio fugaz, sem que ocorra perda de consciência',
'lombalgia': 'Dor na região lombar',
'mácula': 'Pequena mancha cutânea plana, sem elevação, com coloração distinta do tecido que a circunda',
'madarose': 'É uma condição que resulta na perda dos cílios, por vezes, as sobrancelhas. Corresponde a um estigma da hanseníase',
'marasmo': 'É uma forma de desnutrição que causa perda do tecido muscular e subcutâneo',
'mastalgia': 'dor nas mamas', 
'mastite': 'inflamação das mamas',
'mecôneo': 'Substância pastosa de cor esverdeada, que é coletada no intestino do feto e constitui as primeiras evacuações dos recém-nascidos. Quando presentes dentro da barriga, pode indicar sofrimento fetal',
'melanoderma': 'Termo para designar um paciente afrodescendente',
'melena': 'Evacuação de fezes de cor negra, que indica presença de sangue digerido no conteúdo fecal. Fezes moles e pastosas, em aspecto de borra de café e com odor bastante fétido',
'melenêmese': 'Vômito em forma de borra de café. Ocorre quando o sangue esteve em contato com o ácido gástrico por um período de tempo',
'menarca': 'Corresponde a primeira menstruação de uma mulher, geralmente por volta dos 12-15 anos',
'menopausa': 'Período da vida da mulher em que cessa a menstruação',
'metástase':  'Presença de tecido tumoral ou neoplásico, localizada em um lugar distante do sítio de origem, por dissiminação hematogênica ou linfática',
'meteorismo': 'Intumescência abdominal resultado do acúmulo de gases no estômago e alças intestinais',
'método não invasivo': 'Procedimentos em que não envolvem instrumentos que rompem a pele ou que penetram fisicamente no organismo',
'metrorragia': 'É o sangramento uterino irregular, fora do período menstrual',
'mialgia': 'dor muscular',
'microcefalia': 'cabeça anormalmente pequena',
'macrocefalia': 'cabeça anormalmente grande',
'microtia': 'orelhas menores que 4 cm verticalmente',
'midríase': 'É a dilatação da pupila em função da contração do músculo dilatado da pupila',
'mioclonia': 'Contração muscular involuntária e súbita',
'miose': 'Contração da pupila. Diminuição do diâmetro pupilar',
'multípara': 'mulher que deu a luz a mais de um filho',
'narcose': 'é o nome dado à alteração do estado de consciência devido à intoxicação por determinadas substâncias, como narcóticos',
'nevo': 'São pequenas manchas ou elevações de coloração acastanhada ou enegrecida na pele e que aparecem nas primeiras décadas de vida em quase todas as pessoas',
'nictúria': 'maior volume urinário durante a noite do que durante o dia noturno sobre o diurno',
'nistagmo': 'Tremores rítmicos, involuntários e bilaterais dos globos oculares no sentido horizontal, vertical ou rotatório',
'noctúria': 'aumento da frequência de micções à noite',
'nódulo': 'Lesão sólida, elevada, apresentando diâmetro maior que 1 centímetro',
'nucalgia': 'Dor na nuca',
'nulípara': 'mulher que nunca deu à luz',

'obstipação': 'aumento no intervalo entre as evacuações. Acompanhada de fezes ressecadas e dificuldade na eliminação das mesmas. É definida como uma alteração do hábito intestinal na qual o indivíduo fica sem evacuar por mais de 3 dias. Também conhecida como prisão de ventre',
'odinofagia': 'Dor que ocorre durante o processo de deglutição',
'odontalgia': 'dor de dente',
'onicofagia': 'hábito de roer as unhas', 
'oligomenorréia': 'Menstruação irregulares com intervalos prolongados. A presença da oligomenorréia sugere disfunção ovariana',
'oligúria' : 'Redução importante no volume urinário diário, geralmente menor que 100 ml em adultos',
'onicólise': 'Descolamento da unha do leito ungueal, a partir de sua ligação distal ou lateral',
'onicomalácia': 'Unha de consistência amolecida e friável. Sugere sinal de doenças sistêmicas',
'ooforite': 'Inflamação do ovário',
'orquite': 'Processo inflamatório do testículo', 
'ortopnéia': 'Dificuldade para respirar quando o paciente está deitado. Melhora quando o paciente se senta, mantendo o tronco ligeiramente fletido',
'osteomalácia': 'Paciente apresenta amolecimento e curvatura gradual dos ossos com sintomatologia dolorosa de intensidade variável. Resultado da calcificação deficiente em virtude da deficiência de vitamina D. É também conhecida como Raquitismo do adulto',
'otalgia': 'Dor de ouvido',
'otorragia': 'Sangramento expelido pelo ouvido',
'otorréia': 'saída de secreção do ouvido',
'palpitação': 'Percepção subjetica e incômoda de batimento acelerado ou irregular do coração',
'pápula': 'lesão sólida, elevada, apresentando até 1 cm de diâmetro',
'parafimose': 'o prepúcio é retraído e fixo',
'paralisia de Bell': 'Acometimento que ocorre no nervo facial que leva à fraqueza repentina ou à paralisia dos músculos de um dos lados da face',
'paraplegia': 'Paralisia completa de dois segmentos simétricos do corpo, geralmente dos membros inferiores',
'paresia': 'Perda parcial da motricidade, diminuição da força muscular',
'parestesia': 'Aparecimento de sensação anormal e mal definidas, sem prévia estimulação. Dormência e formigamento são os representantes mais significativos da parestesia',
'paroníquia': 'É uma infecção da pele que situa-se ao redor das unhas dos dedos das mãos ou dos pés',
'petéquias': 'pequenas hemorragias puntiformes de 1 a 3 mm, arredondadas e discretas, com cor púrpura ou marrom', 
'pinguécula': 'nódulos elevados e amarelados que surgem a partir de um espessamento da conjuntiva bulbar pela exposição prolongada ao sol, vento e poeira',
'pirexia': 'aumento da temperatura corporal acima dos níveis normais para o indivíduo',
'pectorilóquia': 'Palavra pode ser ouvida com nitidez durante o processo de ausculta pulmonar', 
'pênfigo': 'Denominação geral a um grupo de doenças autoimunes, pouco frequentes, consistindo em dermatoses crônicas, recidivastes e algumas vezes fatais. São caracterizadas clinicamente pelo aparecimento de sucessivos grupos de vesículas e bolhas, inicialmente na mucosa bucal ou orofaríngea e, depois, na pele aparentemente sadia. As bolhas se rompem deixando uma zona erodida, posteriormente recoberta por crostas. A epiderme descola-se facilmente do plano subjacente',
'pirose': 'Sensação de calor ou queimação no estômago. Conhecida como azia',
'piúria': 'Presença de pus na urina',
'plegia': 'Perda de força muscular ou paralisia',
'pletória': 'Aumento local ou geral da massa sanguínea. Quando local pode ser denominado de congestão.',
'polaciúria': 'Aumento da frequência urinária, sem relação com o volume de urina excretado',
'polidactilia': 'presença de dígitos extras',
'polidipsia': 'Termo que refere a sede excessiva',
'polifagia': 'Fome excessiva',
'poliúria': 'Aumento no volume normal de urina excretado nas 24 horas',
'priapismo': 'Ereção prolongada, não associada com estimulação sexual e geralmente dolorosa',
'proctite': 'Inflamação da mucosa do reto',
'pródromo': 'Manifestação clínica ou sintomática que antecede uma doença',
'proptose': 'Deslocamento de um órgão para frente',
'pterígio': 'Tecido fibrovascular recoberto pela conjuntiva ocular, de forma triangular e geralmente localizado no canto interno do olho',
'ptose palpebral': 'Queda da pálpebra associada a lesão do nervo oculomotor',
'pústula': 'Vesícula de conteúdo purulento',
'puxo': 'Contração espasmódica do reto que precede as evacuações',
'presbiacusia': 'é uma perda sensorioneural gradual causada pela degeneração na orelha interna que progride lentamente após a quinta década',
'presbiopia': 'diminuição do poder de acomodação visual com o envelhecimento',
'queilite': 'rachadura nos cantos da boca', 
'queloide': 'é uma cicatriz hipertrófica onde o nível da pele resultante está elevado pelo excesso de tecido cicatricial, que invade além do local original da lesão', 'queratose': 'são áreas elevadas e espessadas de pigmentação que aparecem com crostas, camadas e verrugas',
'rash': 'Erupção de coloração avermelhada, eritematosa em pele como resultado de uma reação alérgica ou infecção. Sinonimo de exantema',
'regurgitação': 'Retorno à boca ou garganta do alimento recém ingerido sem esforço de vômito, ocasionado por refluxo intenso',
'ressecção': 'Extirpação cirúrgica parcial ou total de um órgão',
'rinite': 'Inflamação do nariz',
'rinorréia': 'Secreção nasal',
'salicismo': 'Intoxicação por ácido salicílico, aspirina',
'sepse': 'antiga septicemia. Disseminação de bactérias patogênicas partir de um foco de infecção através da circulação sistêmica',
'sindactilia': 'presença de dedos ligados', 
'sinusite': 'inflamação dos seios paranasais',
'sialorréia': 'Aumento da secreção de saliva',
'sialosquise': 'Diminuição da secreção de saliva', 
'sinal patognomônico': 'Manifestação específica de uma entidade patológica',
'síncope': 'perda súbita da consciência, geralmente acompanhada de perda do tônus postural',
'síndrome': 'Conjunto de sinais e sintomas de mesma marcha evolutiva, porém de causas diversas, que caracterizam um estado mórbido e que se repete na população',
'sintoma': 'Manifestação subjetiva de uma doença. Também é uma percepção normal que uma pessoa tem de seu próprio corpo',
'supuração': 'Presença de secreção purulenta',
'taquicardia': 'Aceleração dos batimentos cardíacos, comumente considerado acima de 100 batimentos por minuto',
'taquipnéia': 'Aumento da frequência respiratória',
'tenesmo': 'Espasmo doloroso do esfíncter anal ou vesical com desejo urgente de defecar ou urinar. Há eliminação de quantidade mínima de fezes ou urina',
'tique': 'Movimento repetido irregular espasmódico',
'trepanação': 'É uma intervenção cirúrgica, em que um buraco (fenestra) é aberto no crânio humano',
'tumor': 'Lesão sólida, elevada, com mais de 3 cm de diâmetro',
'telangiectasia': 'vasos sanguíneos dilatados e permanentemente aumentados que são visíveis na superfície da pele', 
'tricotilomania': 'perda traumática autoinduzida do cabelo, usualmente como resultado do retorcimento ou arrancamento compulsivo',
'tricotomia': 'é um procedimento pré-cirúrgico que tem como objetivo remover os pelos da região a ser cortada para facilitar a visualização da região pelo médico e evitar possíveis infecções após a cirurgia e, consequentemente, complicações para o paciente',
'úlcera': 'perda de resvestimento epitelial deixando o tecido conjuntivo ou derme desnuda',
'unhas de Lindsay': 'Unhas apresentando metade proximal de cor branca, 20-50% distal vermelho. Ocorre na insuficiência renal',
'unhas hipocráticas': 'Unhas recurvadas, em padrão de vidro de relógio, com baqueteamento digital',
'urtica': 'Pápula eritêmato-edematosa, de duração efêmera que tem frequentemente a borda irregular com aspecto de irregular. Pode coalescer e formar placa eritematosa',
'uretrite': 'inflamação da uretra', 
'urticária': 'pápulas que coalescem para forma uma extensa reação, intensamente pruriginosa',
'vaginismo': 'Contração involuntária da vagina',
'vaginite': 'Inflamação da mucosa que reveste a vagina',
'verruga': 'Vegetação de superfície queratótica, de aspecto irregular',
'vegetações': 'Projeções sólidas, digitiformes, moles, por vezes sangrantes e de tamanhos variáveis',
'vertigem': 'Sensação de rotação do organismo em relação ao ambiente ou do ambiente em relação ao organismo por alteração do sistema laberíntico ou cerebelar',
'vesícula': 'Coleção líquida, elevada, com diâmetro de até 1 cm',
'xantelasma': 'manchas ou placas amarelas que surge na região das pálpebras, provocada pelo depósito de lipídeos',
'xantoderma': 'Termo para designar paciente nipônico, pele de cor amarela',
'xantomatose': 'Acúmulo de excesso de lipídios no organismo por alteração metabólica ou formação de tumores',
'xeroftalmia': 'Perda da secreção lacrimal e caracterização de ressecamento excessivo das mucosas que revestem o olho', 
'xerostomia': 'Ressecamento da boca em resultado pela secreção insuficiente ou ausente das glândulas salivares'


};
