module.exports = [
{'name': 'abscesso', 'description': 'constitui uma coleção de pus ou material purulento, comumente associado a uma infecção bacteriana', 'source':
'Semiologia Médica UFOP'},
{'name': 'abulia', 'description': 'perturbação ou Alteração fisiopatológica caracterizada por diminuição ou supressão da vontade', 'source': 'Semiologia Médica UFOP'},
{'name': 'acalásia', 'description': 'compreende a ausência de relaxamento dos esfíncteres. Comumente decorrente de distúrbio nervoso ou por causa desconhecida', 'source': 'Semiologia Médica UFOP'},
{'name': 'acrocianose', 'description': 'distúrbio circulatório que manifesta-se em extremidades tornando-as frias e de coloração azulada. Ocorre principalmente em mãos, e menos comumente os pés, algumas manifestações de acrocianose estão associadas ao fenômeno de Raynaud', 'source': 'Semiologia Médica UFOP'},
{'name': 'acrocórdon', 'description': 'também chamados de pólipos cutâneos, são crescimentos exagerados da pele normal que formam uma haste e são parecidos com pólipos', 'source': 'Rômulo Passos'},
{'name': 'acromegalia', 'description': 'é um distúrbio representado pelo aumento desproporcional dos membros e face, associados a hiperfunção da hipófise', 'source': 'Semiologia Médica UFOP'},
{'name': 'adenite', 'description': 'inflamação ou ingurgitamento de uma glândula ou gânglio linfático', 'source': 'Semiologia Médica UFOP'},
{'name': 'adenomegalia', 'description': ' hipertrofia de um gânglio linfático', 'source': 'Semiologia Médica UFOP'},
{'name': 'adipsia', 'description': 'falta de sede', 'source': 'Semiologia Médica UFOP'},
{'name': 'aerofagia', 'description': 'ato de deglutir ar que é acometido por algumas pessoas, especialmente as que sofrem de dispepsia ou de certos estados ansiosos, neuróticos ou mesmo em situações que levem um indivíduo à uma agitação física e psíquica', 'source': 'Semiologia Médica UFOP'},
{'name': 'afagia', 'description': 'impossibilidade de deglutir', 'source': 'Semiologia Médica UFOP'},
{'name': 'afasia', 'description': 'sintoma neurológico revelado por perda ou incapacidade de expressar ou interpretar a linguagem falada ou escrita', 'source': 'Semiologia Médica UFOP'},
{'name': 'afebril', 'description': 'sem febre', 'source': 'Semiologia Médica UFOP'},
{'name': 'aférese', 'description': 'remoção do sangue do próprio paciente', 'source': 'Semiologia Médica UFOP'},
{'name': 'agalactia', 'description': 'ausência de leite nas mamas depois do parto; agalactose', 'source': 'Semiologia Médica UFOP'},
{'name': 'ageusia', 'description': 'ausência ou redução do sentido do paladar', 'source': 'Semiologia Médica UFOP'},
{'name': 'aglossia', 'description': 'ausência congênita da língua', 'source': 'Semiologia Médica UFOP'},
{'name': 'agnosia', 'description': 'é uma perturbação que se caracteriza pelo fato de a pessoa poder ver e sentir os objetos', 'source': 'Semiologia Médica UFOP'},
{'name': 'agorafobia', 'description': 'distúrbio caracterizado pela sensação de medo de estar só em espaço aberto', 'source': 'Semiologia Médica UFOP'},
{'name': 'agrafia', 'description': 'é uma incapacidade para traduzir as idéias por escrito, apesar de não haver nenhum comprometimento psicomotor, da fala ou da compreensão', 'source': 'Semiologia Médica UFOP'},
{'name': 'alodinia', 'description': 'envolve uma mudança no sentido da dor, da qualidade de uma sensação, seja do tipo que for', 'source': 'Semiologia Médica UFOP'},
{'name': 'alopécia', 'description': 'é a redução parcial ou total de pelos ou cabelos em uma determinada área de pele', 'source': 'Semiologia Médica UFOP'},
{'name': 'amaurose', 'description': 'é um distúrbio caracterizado pela perda total da visão', 'source': 'Semiologia Médica UFOP'},
{'name': 'amenorréia', 'description': 'ausência de mestruação', 'source': 'Rômulo Passos'},
{'name': 'anacusia', 'description': 'total perda da capacidade auditiva', 'source': 'Semiologia Médica UFOP'},
{'name': 'anafrodisia', 'description': 'corresponde a falta de desejo sexual. Frigidez', 'source': 'Semiologia Médica UFOP'},
{'name': 'analgesia', 'description': 'perda ou ausência de sensibilidade dolorosa', 'source': 'Semiologia Médica UFOP'},
{'name': 'anasarca', 'description': 'acúmulo generalizado de líquidos entre os tecidos ou edema generalizado', 'source': 'Semiologia Médica UFOP'},
{'name': 'anastomose', 'description': 'união entre estruturas tubulares', 'source': 'Semiologia Médica UFOP'},
{'name': 'anciloglossia', 'description': 'encurtamento do frênulo da língua', 'source': 'Rômulo Passos'},
{'name': 'anestesia', 'description': 'ausência de sensibilidade tátil', 'source': 'Rômulo Passos'},
{'name': 'aneurisma', 'description': 'alargamento de forma anormal da luz de um vaso sanguíneo', 'source': 'Semiologia Médica UFOP'},
{'name': 'angina', 'description': 'termo médico utilizado para se referir à sensação opressiva que decorre da falta de oxigênaçã do músculo cardíaco', 'source': 'Semiologia Médica UFOP'},
{'name': 'anisocoria', 'description': 'tamanho desigual das pupilas', 'source': 'Rômulo Passos' },
{'name': 'anorexia', 'description': 'distúrbio alimentar que leva a pessoa a ter uma visão distorcida do seu corpo', 'source': 'Semiologia Médica UFOP'},
{'name': 'anosmia', 'description': 'diminuição ou perda total do olfato', 'source': ' Semiologia Médica UFOP'},
{'name': 'anciloglossia', 'description': 'distúrbio de desenvolvimento revelado pela presença de freio lingual curto, leva ao fenômeno conhecido como língua presa', 'source': ' Semiologia Médica UFOP'},
{'name': 'anquilose', 'description': 'imobilidade de uma articulação', 'source': ' Semiologia Médica UFOP'},
{'name': 'anúria', 'description': 'ausência de secreção urinária', 'source': ' Semiologia Médica UFOP'},
{'name': 'apnéia', 'description': 'supressão momentânea da respiração', 'source': ' Semiologia Médica UFOP'},
{'name': 'apnéia do sono', 'description': 'é um distúrbio do sono potencialmente grave em que a respiração cessa e começa repetidamente', 'source': ' Semiologia Médica UFOP'},
{'name': 'apraxia', 'description': 'é um distúrbio neurológico revelado pela incapacidade de executar movimentos coordenados', 'source': ' Semiologia Médica UFOP'},
{'name': 'artralgia', 'description': 'dor em articulações', 'source': ' Semiologia Médica UFOP'},
{'name': 'artrite', 'description': 'inflamação que acomete articulações',  'source': ' Semiologia Médica UFOP'},
{'name': 'artrose', 'description': 'condição degenerativa representada pelo adelgaçamento ou destruição da cartilagem articular e deformação das superfície óssea de uma ou mais articulações', 'source': ' Semiologia Médica UFOP'},
{'name': 'ascite', 'description': 'acúmulo anormal de líquidos dentro da cavidade peritoneal', 'source': 'Rômulo Passos'},
{'name': 'astenia', 'description': 'ausência ou perda de força muscular', 'source': 'Semiologia Médica UFOP'},
{'name': 'ataxia', 'description': 'falta de coordenação de movimentos musculares voluntaries ou mesmo de equilíbrio', 'source': 'Semiologia Médica UFOP'},
{'name': 'atelectasia', 'description': 'é um colapso completo ou parcial de um pulmão ou do lóbulo de um pulmão. Devido ao efeito da anestesia nos pulmões, quase todas as pessoas que passam por cirurgia sofrem atelectasia. Objetos inalados, asma e outras doenças e lesões pulmonares também podem causar o problema', 'source': 'Hospital Albert Einstein'},
{'name': 'atetose', 'description': 'consequência de lesões centrais, caracterizada por apresentar movimentos irregulares e arrítmicos de mãos, pés associado a distensões e contrações dos dedos', 'source': 'Semiologia Médica UFOP'},
{'name': 'atresia', 'description': 'estreitamento ou oclusão de qualquer canal do corpo', 'source': 'Semiologia Médica UFOP'},
{'name': 'atrofia', 'description': 'perda de massa muscular', 'source': 'Rômulo Passos'},
{'name': 'baqueamento digital' , 'description': 'conhecido também por unhas em Vidro de relógio ou hipocráticas. Ocorre quando o ângulo do leito ungueal é maior que 180 graus. Comum em doenças que comprometem a circulação pulmonar', 'source': 'Rômulo Passos'},
{'name': 'bexiga neurogênica' , 'description': 'A bexiga neurogênica é a falta de controle da bexiga devido a um problema nervoso como acidente vascular cerebral, lesão da medula espinhal ou tumor. A incontinência urinária é o sintoma principal', 'source': 'Ministério da Saúde'},
{'name': 'blefarite', 'description': 'inflamação das pálpebras', 'source': 'Rômulo Passos'},
{'name': 'bócio', 'description': 'aumento de volume crônico da tireoide que ocorre em algumas regiões do mundo com dieta pobre em iodo', 'source': 'Rômulo Passos'},
{'name': 'bolha', 'description': 'termo semiológico que se refere à uma lesão elevada, maior que 1 cm de diâmetro e que apresenta acúmulo de liquido de aspecto claro ou citrino. Ocorre prevalentemente entre as camadas superficiais da epiderme ou mucosa', 'source': 'Semiologia Médica UFOP'},
{'name': 'bradicardia', 'description': 'diminuição da frequência cardíaca a menos de 60 batimentos por minuto', 'source': 'Semiologia Médica UFOP'},
{'name': 'bradicinesia', 'description': 'termo médico que define a lentidão anormal ', 'source': 'Semiologia Médica UFOP'},
{'name': 'bradipneia', 'description': 'respiração lenta. Frequência ventilatória diminuída, abaixo de 8 inspirações por minuto', 'source': 'Semiologia Médica UFOP'},
{'name': 'bronquiectasia', 'description': 'é uma condição em que as vias aéreas dos pulmões são danificadas, dificultando a secreção de muco. Ela pode ser resultado de uma infecção ou condição médica, como pneumonia ou fibrose cística. O muco acumula-se e gera bactérias, causando infecções frequentes', 'source': 'Hospital Albert Einstein'},
{'name': 'bruxismo', 'description': 'trata-se de uma atividade muscular parafuncional  e repetitiva da mandíbula, que tem como característica o apertar, ranger ou bater os dentes, o que pode ocorrer apoiando ou empurrando a mesma estrutura óssea', 'source': 'UOL.'},
{'name': 'bulimia', 'description': 'é a ingesta compulsiva de alimentos, comumente seguida de indução de vômitos', 'source': 'Semiologia Médica UFOP'},
{'name': 'cacifo', 'description': 'sinal clinico avaliado por meio de pressão digital sobre um edema de pele. Considera-se cacifo positivo em áreas onde a compressão não se desfaz imediatamente após a remoção da pressão digital', 'source': 'Semiologia Médica UFOP'},
{'name': 'cacofagia', 'description': 'estado mórbido em que o paciente apresenta perversão do apetite, fazendo-o ingerir substâncias consideradas repugnantes, como exemplo fezes', 'source': 'Semiologia Médica UFOP'},
{'name': 'cacosmia', 'description': 'indivíduo que aprecia ou sente atração por cheiros desagradáveis', 'source': 'Semiologia Médica UFOP'},
{'name': 'calázio', 'description': 'condição inflamatória caracterizada por pequeno nódulo localizado em região inferior ou superior das pálpebras causado pelo bloqueio dos orifícios das glândulas palpebrais', 'source': 'Semiologia Médica UFOP'},
{'name': 'calvície', 'description': 'também denominada de alopécia androgênica. É uma afecção, comum no homem e rara na mulher, representada por perda de cabelos', 'source': 'Semiologia Médica UFOP'},
{'name': 'canície', 'description': 'despigmentação capilar que surge fisiologicamente a partir da terceira década de vida', 'source': 'Semiologia Médica UFOP'},
{'name': 'caquexia', 'description': 'emagrecimento extremo com comprometimento franco do estado geral e incapacidade de desempenhar atividades mínimas', 'source': 'Semiologia Médica UFOP'},
{'name': 'catatonia', 'description': 'quadro clinico onde ocorre uma perturbação da iniciativa e comportamento motor, bem como do grau de tensão muscular. É comum em transtornos psiquiátricos', 'source': 'Semiologia Médica UFOP'},
{'name': 'cefaleia', 'description': 'dor de cabeça', 'source': 'Semiologia Médica UFOP'},
{'name': 'celulite', 'description': 'inflamação de tecido conjuntivo subcutâneo frouxo', 'source': 'Rômulo Passos'},
{'name': 'ceratite', 'description': 'inflamação na córnea', 'source': 'Semiologia Médica UFOP'},
{'name': 'ceratocone', 'description': 'é uma condição patológica que afeta o formato e a espessura da córnea, como resultado, o paciente apresenta percepção distorcida de imagens', 'source': 'Semiologia Médica UFOP'},
{'name': 'cervicalgia', 'description': 'dor localizada na região cervical, isto é na parte posterior do pescoço ou nuca', 'source': 'Semiologia Médica UFOP'},
{'name': 'cervicite', 'description': 'inflamação localizada no colo uterino', 'source': 'Semiologia Médica UFOP'},
{'name': 'choque anafilático', 'description': 'constitui uma reação alérgica grave, resultando em diminuição da pressão arterial, taquicardia, acompanhado ou não de edema de glote', 'source': 'Semiologia Médica UFOP'},
{'name': 'choque séptico', 'description':'é o termo médico utilizado para designar a falência circulatório aguda por causa infecciosa', 'source': 'Semiologia Médica UFOP'},
{'name': 'choque', 'description': 'sofrimento celular fruto da falta de irrigação sanguínea', 'source': 'Semiologia Médica UFOP'},
{'name': 'cianose', 'description': 'sinal onde o paciente apresenta cor azulada ou arroxeada da pele e das mucosas, decorrente da diminuição da oxigenação tecidual', 'source': 'Semiologia Médica UFOP'},
{'name': 'cistite', 'description': 'inflamação da bexiga', 'source': 'Rômulo Passos'},
{'name': 'cisto', 'description': 'cavidade encapsulada cheia de líquido na derme ou camada subcutânea, elevando a pele sob tensão', 'source': 'Rômulo Passos'},
{'name': 'claudicação', 'description': 'é um termo médico para designar distúrbio de marcha devido a diferenças anatômicas ou funcionais entre os membros inferiores', 'source': 'Semiologia Médica UFOP'},
{'name': 'cloasma', 'description': 'é uma área acastanhada irregular de hiper-pigmentação na face', 'source': 'Rômulo Passos'},
{'name': 'clônus', 'description': 'série de contrações involuntárias devido a um estiramento súbito do músculo', 'source': 'Semiologia Médica UFOP'},
{'name': 'coiloníquia', 'description': 'unha em forma de colher', 'source': 'Semiologia Médica UFOP'},
{'name': 'coitarca', 'description': 'idade da primeira atividade sexual', 'source': 'R6omulo Passos'},
{'name': 'colêmese', 'description': 'vômito com bile', 'source': 'Semiologia Médica UFOP'},
{'name': 'colestase', 'description': 'iminuição ou interrupção do fluxo da bilis como resultado de retenção do conteúdo biliar no parênquima hepático', 'source': 'Semiologia Médica UFOP'},
{'name': 'colite', 'description': 'inflamação do cólon', 'source': 'Semiologia Médica UFOP'},
{'name': 'conjuntivite', 'description': 'inflamação da conjuntiva', 'source': 'Rômulo Passos'},
{'name': 'constipação', 'description': 'afecção produzida por alteração de transito intestinal, gerando retenção de fezes ou dificuldade de sua evacuação', 'source': 'Semiologia Médica UFOP'},
{'name': 'coriza', 'description': 'corrimento de secreção nasal', 'source': 'Semiologia Médica UFOP'},
{'name': 'criptoquirdia', 'description': 'testículos não descidos', 'source': 'Rômulo Passos'},
{'name': 'dacriocistite', 'description': 'Infecção do saco lacrimal, geralmente devido a bloqueio do canal nasolacrimal', 'source': 'Manual MSD Versão para família'},
{'name': 'delírio', 'description': 'Alteração aguda da consciência ou da lucidez, fruto de um distúrbio orgânica', 'source': 'Semiologia Médica UFOP'},
{'name': 'derrame pleural', 'description': 'acúmulo de líquido no espaço pleural do tórax', 'source': 'Semiologia Médica UFOP'},
{'name': 'derrame', 'description': 'Acúmulo anormal de liquido em qualquer cavidade ou órgão', 'source': 'Semiologia Médica UFOP'},
{'name': 'diabetes', 'description': 'É uma doença crônica caracterizada pelo aumento dos níveis de açúcar no sangue', 'source': 'site tua saúde'},
{'name': 'diarréia', 'description': 'Tecnicamente consiste em evacuação de mais de 200 g de fezes ao dia. É uma também uma perturbação intestinal caracterizada por aumento frequência de evacuações', 'source': 'Semiologia Médica UFOP'},
{'name': 'diérese', 'description': 'Segmentação de fragmentos de tecidos orgânicos normalmente unidas, de forma acidental ou cirúrgica, sem perda de substância', 'source': 'Semiologia Médica UFOP'},
{'name': 'diplopia', 'description': 'Presença de visão dupla relatada pelo paciente, ocorre comumente em estrabismo', 'source': 'Semiologia Médica UFOP'},
{'name': 'disacusia', 'description': 'Estado mórbido em que sons produzem distúrbio da audição, dor ou mal-estar', 'source': 'Semiologia Médica UFOP'},
{'name': 'disartria', 'description': 'dificuldade na articulação da fala', 'source': 'Semiologia Médica UFOP'},
{'name': 'disdiadococinesia', 'description': 'Incapacidade de realizar eficientemente movimentos rápidos e alternados. Ocorre comumente em doença cerebelar', 'source': 'Semiologia Médica UFOP'},
{'name': 'disenteria', 'description': 'Diarréia com a presença de muco, pus ou sangue nas fezes e dor à evacuação', 'source': 'Semiologia Médica UFOP'},
{'name': 'disfagia', 'description': 'Distúrbio em que o paciente apresenta dificuldade de deglutição', 'source': 'Semiologia Médica UFOP'},
{'name': 'disfasia', 'description': 'Perturbação na compreensão ou expressão da linguagem', 'source': 'Semiologia Médica UFOP'},
{'name': 'disfonia', 'description': 'Alteração ou dificuldade da produção normal da voz', 'source': 'Semiologia Médica UFOP'},
{'name': 'dislalia', 'description': 'é um distúrbio da fala, caracterizado pela dificuldade em articular as palavras. Basicamente consiste na má pronúncia das palavras, seja omitindo ou acrescentando fonemas, trocando um fonema por outro ou ainda distorcendo-os ordenadamente', 'source': 'Rômulo Passos'},
{'name': 'dislexia', 'description': 'Disfasia escrita ou dificuldade de leitura, apesar da visão e da articulação das palavras apresentarem-se normais. Resulta de um defeito da habilidade de processar símbolos gráficos', 'source': 'Semiologia Médica UFOP'},
{'name': 'dismenorréia', 'description': 'Dor associada à menstruação', 'source': 'Semiologia Médica UFOP'},
{'name': 'dismetria', 'description': 'incapacidade controlar a distância, a força e a velocidade de uma ação muscular', 'source': 'Rômulo Passos'},
{'name': 'dispareunia', 'description': 'dor durante a relação sexual', 'source': 'Semiologia Médica UFOP'},
{'name': 'dispepsia', 'description': 'É um conjunto de sinais relacionados ao trato gastro intestinal com odor, queimação ou desconforto na região superior do abdomen', 'source': 'Semiologia Médica UFOP'},
{'name': 'dispnéia paroxística', 'description': 'Dificuldade da respiração que surge em crises, comumente à noite quando o paciente deita. Comumente conhecida como dispnéia paroxística noturna', 'source': 'Semiologia Médica UFOP'},
{'name': 'dispnéia', 'description': 'Dificuldade para respirar, sensação subjetiva de falta de ar ao nível de trato respiratório inferior', 'source': 'Semiologia Médica UFOP'},
{'name': 'disquesia', 'description': 'evacuação dolorosa', 'source': 'Semiologia Médica UFOP'},
{'name': 'distaxia', 'description': 'Dificuldade na coordenação de movimentos musculares voluntaries ou de equilíbrio', 'source': 'Semiologia Médica UFOP'},
{'name': 'distonia', 'description': 'Movimento ou postura anormal mantida, devido à alteração do tônus', 'source': 'Semiologia Médica UFOP'},
{'name': 'disúria', 'description': 'Micção difícil ou dolorosa', 'source': 'Semiologia Médica UFOP'},
{'name': 'diverticulite', 'description': 'Inflamação aguda da parede de um divertículo do cólon', 'source': 'Semiologia Médica UFOP'},
{'name': 'divertículo', 'description': 'Eventração de parte da mucosa do colon através de uma área enfraquecida da parede intestinal', 'source': 'Semiologia Médica UFOP'},
{'name': 'edema', 'description': 'Acúmulo anormal de liquido localizado nos espaços intercelulares dos tecidos ou em diferentes cavidades corpóreas', 'source': 'Semiologia Médica UFOP'},
{'name': 'efélides', 'description': 'São manchas ou máculas causadas pelo aumento de melanina na pele e estimuladas pela exposição ao sol. Popularmente chamadas de sardas', 'source': 'Semiologia Médica UFOP'},
{'name': 'embolia', 'description': 'Presença de uma substância sólida, líquida ou gasosa no circuito arterial com a consequente obstrução do fluxo', 'source': 'Semiologia Médica UFOP'},
{'name': 'êmese', 'description': 'vômito', 'source': 'Semiologia Médica UFOP'},
{'name': 'encoprese', 'description': 'Emissão involuntária de fezes, após a idade na qual o controle dos esfíncteres já deveria existir', 'source': 'Semiologia Médica UFOP'},
{'name': 'enema', 'description': 'Inserção de substâncias líquidas ou semilíquidas através do esfíncter anal, para induzir a defecação ou administrar medicamentos', 'source': 'Semiologia Médica UFOP'},
{'name': 'enfisema', 'description': 'condição patológica caracterizada por destruição das paredes dos alvéolos pulmonares', 'source': 'Semiologia Médica UFOP'},
{'name': 'enoftalmia', 'description': 'Retração do globo ocular, posição profunda do globo ocular na órbita', 'source': 'Semiologia Médica UFOP'},
{'name': 'enterorragia', 'description': 'Hemorragia intestinal com eliminação de sangue vivo pelo ânus', 'source': 'Semiologia Médica UFOP'},
{'name': 'enurese', 'description': 'Emissão involuntária de urina durante a noite', 'source': 'Semiologia Médica UFOP'},
{'name': 'epididimite', 'description': 'inflamação do epidídimo', 'source': 'Rômulo Passos'},
{'name': 'epífora', 'description': 'lacrimejamento excessivo', 'source': 'Rômulo Passos'},
{'name': 'episiotomia', 'description': 'Incisão ao nível do assoalho perineal, visando ampliar o canal do parto, facilitando o desprendimento fetal', 'source': 'Semiologia Médica UFOP'},
{'name': 'epispádia', 'description': 'Abertura da uretra em qualquer região da face dorsal da haste peniana', 'source': 'Semiologia Médica UFOP'},
{'name': 'epistaxe', 'description': 'Hemorragia de origem nasal', 'source': 'Semiologia Médica UFOP'},
{'name': 'epúlide', 'description': 'um nódulo não sensível e fibroso da gengiva, que emerge entre os dentes; uma resposta inflamatória à lesão ou hemorragia', 'source': 'Rômulo Passos'},
{'name': 'equimose', 'description': 'Mancha amarronada/acastanhada, resultante do extravasamento de sangue no tecido subcutâneo resultado de uma ruptura capilar', 'source': 'Semiologia Médica UFOP'},
{'name': 'erisipela', 'description': 'Infecção cutânea que acomete derme e tecido subcutâneo, produzida por estreptococus', 'source': 'Semiologia Médica UFOP'},
{'name': 'eritema', 'description': 'Também denominado de rubor, consiste de um sinal clinico caracterizado por uma coloração avermelhada ocasionada por vasodilatação vascular', 'source': 'Semiologia Médica UFOP'},
{'name': 'eritrodermia', 'description': 'Eritema ou ruborização generalizada em pele', 'source': 'Semiologia Médica UFOP'},
{'name': 'eructação', 'description': 'Expulsão súbita, por vezes ruidosa, de gases pela boca. popularmente denominado arroto. Tem como causa principal a aerofagia', 'source': 'Semiologia Médica UFOP'},
{'name': 'escama', 'description': 'flocos compactados e ressecados de pele, secos ou gordurosos, prateados ou brancos, pele descolamento do excesso de células queratinizadas mortas', 'source': 'Semiologia Médica UFOP'},
{'name': 'esclerodermia', 'description': 'é um distúrbio crônico do tecido conjuntivo associado com a diminuição do turgor cutâneo, isto é, literalmente um enrijecimento da pele', 'source': 'Rômulo Passos'},
{'name': 'esclerose múltipla' , 'description': 'doença em que o sistema imunológico destroi a cobertura protetora dos nervos', 'source': 'Semiologia Médica UFOP'},
{'name': 'escoriação', 'description': 'abrasão autoinfligida, superficial, às vezes em crosta, escarificações pela coceira excessiva', 'source': 'Rômulo Passos'},
{'name': 'escotoma', 'description': 'É uma região do campo visual que apresenta perda total ou parcial da acuidade visual, cerceada por área de visão normal', 'source': 'Semiologia Médica UFOP'},
{'name': 'esteatorréia', 'description': 'Presença de quantidade anormal e excessiva de gorduras nas fezes', 'source': 'Semiologia Médica UFOP'},
{'name': 'estomatite', 'description': 'inflamação da boca', 'source': 'Rômulo Passos'},
{'name': 'estrabismo', 'description': 'é um Distúrbio em que os olhos não olham exatamente na mesma direção ao mesmo tempo. As   causas de estrabismo podem incluir lesão do nervo ou disfunção dos músculos que controlam o olho', 'source': 'Hospital Albert Einstein'},
{'name': 'estridor', 'description': 'Ruído respiratório áspero, de tonalidade alta, ocorre por obstrução das vias aéreas altas', 'source': 'Semiologia Médica UFOP'},
{'name': 'exantema', 'description': 'erupção eritematosa generalizada e aguda, de curta duração', 'source': 'Semiologia Médica UFOP'},
{'name': 'exoftalmia', 'description': 'projeção do globo ocular para frente', 'source': 'Semiologia Médica UFOP'},
{'name': 'exsulceração', 'description': 'Processo patológico de formação de uma úlcera', 'source': 'Semiologia Médica UFOP'},
{'name': 'fasciculação', 'description': 'São contrações irregulares e não rítmicas de fascículos musculares, mesmo no estado de repouso. Essa condição desaparece com o a movimentação voluntária da musculatura', 'source': 'Semiologia Médica UFOP'},
{'name': 'fenômeno de Raynaud' , 'description': 'É uma condição na qual ocorre um exagero na resposta à temperatura fria. são afecções nas quais as arteríolas, geralmente dos dedos das mãos e dos pés, sofrem um espasmo e, em consequência, a pele torna-se pálida ou com manchas vermelhas e, posteriormente, azuis', 'source': 'Semiologia Médica UFOP'},
{'name': 'fimose', 'description': 'Condição na qual é impossível retrair o prepúcio sobre a glande, de forma a exteriorizá-la', 'source': 'Semiologia Médica UFOP'},
{'name': 'fissura', 'description': 'ruptura linear com margens abruptas, estendendo até derme, seca ou úmida', 'source': 'Rômulo Passos'},
{'name': 'flatulência', 'description': 'Corresponde ao acúmulo anormal de gases no estômago e/ou intestinos', 'source': 'Semiologia Médica UFOP'},
{'name': 'flebite', 'description': 'São inflamações que ocorrem em veias', 'source': 'Semiologia Médica UFOP'},
{'name': 'flictena', 'description': 'cavidade elevada contendo líquido maior de 1 cm', 'source': 'Rômulo Passos'},
{'name': 'foliculite', 'description': 'infecção superficial dos folículos pilosos', 'source': 'Semiologia Médica UFOP'},
{'name': 'fonofobia', 'description': 'Intolerância a ruídos ou sons', 'source': 'Semiologia Médica UFOP'},
{'name': 'fotofobia', 'description': 'Intolerância à luz', 'source': 'Semiologia Médica UFOP'},
{'name': 'frêmito', 'description': 'Sensação vibratória que pode ser percebida ao exame de palpação do tórax de um indivíduo no momento em que ele fala ou no momento em que respira', 'source': 'Semiologia Médica UFOP'},
{'name': 'frigidez', 'description': 'Insensibilidade sexual, anafrodisia', 'source': 'Semiologia Médica UFOP'},
{'name': 'galactorréia', 'description': 'Secreção leitosa por via mamária de forma anormal e fora do período de amamentação', 'source': 'Semiologia Médica UFOP'},
{'name': 'gangrena', 'description': 'Condição de morte celular/tecidual resultado de em consequência de aporte sanguíneo insuficiente e da ação de agentes externos sobre o tecido necrosado', 'source': 'Semiologia Médica UFOP'},
{'name': 'gastrite', 'description': 'Inflamação aguda ou crônica da mucosa estomacal', 'source': 'Semiologia Médica UFOP'},
{'name': 'gengivite', 'description': 'Inflamação na gengiva, sem comprometimento ósseo adjacente', 'source': 'Semiologia Médica UFOP'},
{'name': 'genuvalgo', 'description': 'joelhos para dentro', 'source': 'Rômulo Passos'},
{'name': 'genuvaro', 'description': 'pernas arqueadas', 'source': 'Rômulo Passos'},
{'name': 'ginecomastia', 'description': 'Alargamento benigno da mama masculina que ocorre quando tecidos perféricos convertem hormônios androgênicos em estrogênicos', 'source': 'Rômulo Passos'},
{'name': 'glaucoma', 'description': 'Aumento da pressão intraocular', 'source': 'Semiologia Médica UFOP'},
{'name': 'glicosúria', 'description': 'Presença de glicose na urina', 'source': 'Semiologia Médica UFOP'},
{'name': 'goma', 'description': 'Lesão cuja característica apresenta-se como nódulo ou tumor que se liquefaz na porção central e que pode se ulcerar, eliminando substância necrótica. Comum em lesões de sífilis', 'source': 'Semiologia Médica UFOP'},
{'name': 'halitose', 'description': 'Presença de odor desagradável proveniente da cavidade oral', 'source': 'Semiologia Médica UFOP'},
{'name': 'halo senil' , 'description': 'Também denominado de arco senil ou gerontoxo. Corresponde a formação de um arco ou anel opaco-esbranquiçado opacidade perifericamente a córnea. Sua gênese pode estar associada ao acúmulo de colesterol, fosfolipídios e gorduras neutras; ocorre em pacientes idosos ou em jovens com história de hipercolesterolemia e xantomatose', 'source': 'Semiologia Médica UFOP'},
{'name': 'hematêmese', 'description': 'Eliminação de sangue por meio de vômito proveniente do tubo digestivo', 'source': 'Semiologia Médica UFOP'},
{'name': 'hematoma', 'description': 'Tumefação bem definida que ocorre devido a Coleção sanguínea proveniente de rompimento de vasos sanguíneos', 'source': 'Semiologia Médica UFOP'},
{'name': 'hematoquezia', 'description': 'É um termo médico utilizado para designar a presença de sangue com cor vermelha viva misturado as fezes. A hematoquezia está geralmente associada a uma hemorragia intestinal', 'source': 'Semiologia Médica UFOP'},
{'name': 'hematúria', 'description': 'É a presença de sangue na urina', 'source': 'Rômulo Passos'},
{'name': 'hemiplegia', 'description': 'Paralisia de uma área que afeta metade do corpo', 'source': 'Semiologia Médica UFOP'},
{'name': 'hemoflictema', 'description': 'Vesícula com conteúdo sanguinolento no seu interior', 'source': 'Semiologia Médica UFOP'},
{'name': 'hemoptise', 'description': 'Expulsão ou expectoração sanguínea ou sanguinolenta por meio da tosse, proveniente de hemorragia na árvore respiratória', 'source': 'Semiologia Médica UFOP'},
{'name': 'hemorragia', 'description': 'Extravasamento de sangue do sistema cardiovascular para outra topografia anatômica ou para a porção extracorpórea', 'source': 'Semiologia Médica UFOP'},
{'name': 'hepatite', 'description': 'Inflamação do fígado', 'source': 'Semiologia Médica UFOP'},
{'name': 'hifema', 'description': 'sangue na câmara anterior ocular', 'source': 'Semiologia Médica UFOP'},
{'name': 'hiperalgesia', 'description': 'aumento da sensação de dor', 'source': 'Rômulo Passos'},
{'name': 'hipertensão arterial','description': 'também conhecida como pressão alta, é uma doença que ataca os vasos sanguíneos, coração, cérebro, olhos e rins. Ocorre quando a medida da pressão se mantém frequentemente acima de 140 por 90 mmHg', 'source': 'Ministério da saúde'},
{'name': 'hiperestesia', 'descripition': 'aumento da sensibilidade tátil', 'source': 'Rômulo Passos'},
{'name': 'hipertricose', 'description': 'Aumento do crescimento de pelos, localizada a uma topografia especifica ou generalizada, de caráter genético ou adquirido, que surge comumente em locais normalmente providos de pelos', 'source': 'Semiologia Médica UFOP'},
{'name': 'hiperventilação', 'description': 'aumento na frequência e na profundidade ventilatórias', 'source': 'Rômulo Passos'},
{'name': 'hipoacusia', 'description': 'Diminuição da acuidade auditiva', 'source': 'Semiologia Médica UFOP'},
{'name': 'hipoalgesia', 'description': 'diminuição da sensação de dor', 'source': 'Rômulo Passos'},
{'name': 'hipoestesia', 'description': 'diminuição da sensibilidade tátil', 'source': 'Rômulo Passos'},
{'name': 'hipópio', 'description': 'material purulento na câmara anterior', 'source': 'Rômulo Passos'},
{'name': 'hiposmia', 'description': 'diminuição do olfato', 'source': 'Rômulo Passos'},
{'name': 'hipospádia', 'description': 'Defeito congênito no pênis, onde o meato uretral abre-se ventralmente em qualquer ponto ao longo da haste peniana ou mesmo no períneo', 'source': 'Semiologia Médica UFOP'},
{'name': 'hipotricose', 'description': 'Ausência de pelos ou cabelos em topografia anatômica em que comumente deveriam aparecer', 'source': 'Semiologia Médica UFOP'},
{'name': 'hipoventilação', 'description': 'padrão ventilatório superficial e irregular', 'source': 'Rômulo Passos'},
{'name': 'hirsutismo', 'description': 'É o desenvolvimento na mulher de uma pilosidade excessiva e de feitio masculino em locais normalmente desprovidos de pelos', 'source': 'Semiologia Médica UFOP'},
{'name': 'histerectomia', 'description': 'É a remoção cirúrgica do útero, que também pode incluir a retirada das trompas adjacentes e do ovário', 'source': 'Semiologia Médica UFOP'},
{'name': 'hordéolo', 'description': 'Corresponde ao terçol. É uma infecção estafilocócica localizada na raiz dos folículos, na borda das pálpebras', 'source': 'Semiologia Médica UFOP'},
{'name': 'icterícia', 'description': 'cor amarelada da pele que indica aumento dos níveis de bilirrubina no sangue', 'source': 'Rômulo Passos'},
{'name': 'ictiose', 'description': 'Condição hereditária, onde a pele de um indivíduo apresenta forma semelhante a escamas de peixe. Ocorre principalmente em Síndrome de Zunich', 'source': 'Semiologia Médica UFOP'},
{'name': 'ileite', 'description': 'Inflamação do íleo', 'source': 'Semiologia Médica UFOP'},
{'name': 'incontinência', 'description': 'Perda da capacidade de controlar os esfíncteres anal ou vesical', 'source': 'Semiologia Médica UFOP'},
{'name': 'infarto', 'description': 'Morte de um tecido ou mesmo de um órgão por irrigação sanguínea insuficiente ou inadequada', 'source': 'Semiologia Médica UFOP'},
{'name': 'iridociclite', 'description': 'infecção de um dos anexos da vista', 'source': 'Semiologia Médica UFOP'},
{'name': 'irite', 'description': 'inflamação da íris', 'source': 'Semiologia Médica UFOP'},
{'name': 'lagoftalmia', 'description': 'É uma condição que impede a pessoa de fechar completamente as suas pálpebras', 'source': 'Semiologia Médica UFOP'},
{'name': 'leucocitúria', 'description': 'Presença de leucócitos na urina', 'source': 'Semiologia Médica UFOP'},
{'name': 'leucoderma', 'description': 'Termo para designar um paciente caucasiano', 'source': 'Semiologia Médica UFOP'},
{'name': 'leucoma', 'description': 'É a opacidade corneana. A córnea cursa com aspecto branco em toda sua extensão ou em parte', 'source': 'Semiologia Médica UFOP'},
{'name': 'leuconíquia', 'description': 'também conhecido por linhas de Muehrcke. Presença de linhas brancas transversais nas unhas', 'source': 'Rômulo Passos'},
{'name': 'leucoplasia', 'description': 'Termo clínico usado para designar uma lesão de matiz esbranquiçada em mucosas', 'source': 'Semiologia Médica UFOP'},
{'name': 'leucorreia', 'description': 'Corrimento de coloração esbranquiçada através da vagina ou uretra', 'source': 'Semiologia Médica UFOP'},
{'name': 'leucotricose', 'description': 'Embranquecimento dos cabelos devido à falta de formação de melanina pelos melanócitos da matriz do pelo. Pode ser congênita, causando o albinismo, ou adquirida causando a poliose', 'source': 'Semiologia Médica UFOP'},
{'name': 'leucotríquia anular' , 'description': 'distrofia congênita rara, na qual os cabelos apresentam áreas claras e escuras de forma alternadas', 'source': 'Semiologia Médica UFOP'},
{'name': 'linfadenite', 'description': 'Inflamação dos gânglios linfáticos. Condição que comumente leva a linfadenomegalia', 'source': 'Semiologia Médica UFOP'},
{'name': 'linfadenomegalia', 'description': 'Aumento de linfonodos. Sinônimo de adenomegalia', 'source': 'Semiologia Médica UFOP'},
{'name': 'linfadenopatia', 'description': 'aumento de volume dos linfonodos, maior que 1 centimetro por infecção, alergia ou neoplasia', 'source': 'Rômulo Passos'},
{'name': 'lipotímia', 'description': 'Desfalecimento, desmaio fugaz, sem que ocorra perda de consciência', 'source': 'Semiologia Médica UFOP'},
{'name': 'lombalgia', 'description': 'Dor na região lombar', 'source': 'Semiologia Médica UFOP'},
{'name': 'macrocefalia', 'description': 'cabeça anormalmente grande', 'source': 'Rômulo passos'},
{'name': ' macroglossia', 'description': 'lingua aumentada', 'source': 'Rômulo Passos'},
{'name': ' macrotia', 'description': 'orelhas maiores que 10 cm verticalmente', 'source': 'Rômulo Passos'},
{'name': 'mácula', 'description': 'Pequena mancha cutânea plana, sem elevação, com coloração distinta do tecido que a circunda', 'source': 'Semiologia Médica UFOP'},
{'name': 'madarose', 'description': 'É uma condição que resulta na perda dos cílios, por vezes, as sobrancelhas. Corresponde a um estigma da hanseníase', 'source': 'Semiologia Médica UFOP'},
{'name': 'marasmo', 'description': 'É uma forma de desnutrição que causa perda do tecido muscular e subcutâneo', 'source': 'Semiologia Médica UFOP'},
{'name': 'mastalgia', 'description': 'dor nas mamas', 'source': 'Rômulo Passos'},
{'name': 'mastite', 'description': 'inflamação das mamas', 'source': 'Rômulo Passos'},
{'name': 'mecôneo', 'description': 'Substância pastosa de cor esverdeada, que é coletada no intestino do feto e constitui as primeiras evacuações dos recém-nascidos. Quando presentes dentro da barriga, pode indicar sofrimento fetal', 'source': 'Semiologia Médica UFOP'},
{'name': 'melanoderma', 'description': 'Termo para designar um paciente afrodescendente', 'source': 'Semiologia Médica UFOP'},
{'name': 'melena', 'description': 'Evacuação de fezes de cor negra, que indica presença de sangue digerido no conteúdo fecal. Fezes moles e pastosas, em aspecto de borra de café e com odor bastante fétido', 'source': 'Semiologia Médica UFOP'},
{'name': 'melenêmese', 'description': 'Vômito em forma de borra de café. Ocorre quando o sangue esteve em contato com o ácido gástrico por um período de tempo', 'source': 'Semiologia Médica UFOP'},
{'name': 'menarca', 'description': 'Corresponde a primeira menstruação de uma mulher, geralmente por volta dos 12-15 anos', 'source': 'Semiologia Médica UFOP'},
{'name': 'menopausa', 'description': 'Período da vida da mulher em que cessa a menstruação', 'source': 'Semiologia Médica UFOP'},
{'name': 'metástase', 'description': 'Presença de tecido tumoral ou neoplásico, localizada em um lugar distante do sítio de origem, por dissiminação hematogênica ou linfática', 'source': 'Semiologia Médica UFOP'},
{'name': 'meteorismo', 'description': 'Intumescência abdominal resultado do acúmulo de gases no estômago e alças intestinais', 'source': 'Semiologia Médica UFOP'},
{'name': 'método não invasivo' , 'description': 'Procedimentos em que não envolvem instrumentos que rompem a pele ou que penetram fisicamente no organismo', 'source': 'Semiologia Médica UFOP'},
{'name': 'metrorragia', 'description': 'É o sangramento uterino irregular, fora do período menstrual', 'source': 'Semiologia Médica UFOP'},
{'name': 'mialgia', 'description': 'dor muscular', 'source': 'Rômulo Passos'},
{'name': 'microcefalia', 'description': 'cabeça anormalmente pequena', 'source': 'Rômulo Passos'},
{'name': 'microtia', 'description': 'orelhas menores que 4 cm verticalmente', 'source': 'R6omulo Passos'},
{'name': 'midríase', 'description': 'É a dilatação da pupila em função da contração do músculo dilatado da pupila', 'source': 'Semiologia Médica UFOP'},
{'name': 'mioclonia', 'description': 'Contração muscular involuntária e súbita', 'source': 'Semiologia Médica UFOP'},
{'name': 'miose', 'description': 'Contração da pupila. Diminuição do diâmetro pupilar', 'source': 'Semiologia Médica UFOP'},
{'name': 'multípara', 'description': 'mulher que deu a luz a mais de um filho', 'source': 'Infopédia'},
{'name': 'narcose', 'description': 'é o nome dado à alteração do estado de consciência devido à intoxicação por determinadas substâncias, como narcóticos', 'source': 'Semiologia Médica UFOP'},
{'name': 'nevo', 'description': 'São pequenas manchas ou elevações de coloração acastanhada ou enegrecida na pele e que aparecem nas primeiras décadas de vida em quase todas as pessoas', 'source': 'Semiologia Médica UFOP'},
{'name': 'nictúria', 'description': 'maior volume urinário durante a noite do que durante o dia noturno sobre o diurno', 'source': 'Semiologia Médica UFOP'},
{'name': 'nistagmo', 'description': 'Tremores rítmicos, involuntários e bilaterais dos globos oculares no sentido horizontal, vertical ou rotatório', 'source': 'Semiologia Médica UFOP'},
{'name': 'noctúria', 'description': 'aumento da frequência de micções à noite', 'source': 'Rômulo Passos'},
{'name': 'nódulo', 'description': 'Lesão sólida, elevada, apresentando diâmetro maior que 1 centímetro', 'source': 'Semiologia Médica UFOP'},
{'name': 'nucalgia', 'description': 'Dor na nuca', 'source': 'Semiologia Médica UFOP'},
{'name': 'nulípara', 'description': 'mulher que nunca deu à luz', 'source': 'Semiologia Médica UFOP'},
{'name': 'obstipação', 'description': 'aumento no intervalo entre as evacuações. Acompanhada de fezes ressecadas e dificuldade na eliminação das mesmas. É definida como uma alteração do hábito intestinal na qual o indivíduo fica sem evacuar por mais de 3 dias. Também conhecida como prisão de ventre', 'source': 'Semiologia Médica UFOP'},
{'name': 'odinofagia', 'description': 'Dor que ocorre durante o processo de deglutição', 'source': 'Semiologia Médica UFOP'},
{'name': 'odontalgia', 'description': 'dor de dente', 'source': 'Rômulo Passos'},
{'name': 'oligomenorréia', 'description': 'Menstruação irregulares com intervalos prolongados. A presença da oligomenorréia sugere disfunção ovariana', 'source': 'Semiologia Médica UFOP'},
{'name': 'oligúria', 'description': 'Redução importante no volume urinário diário, geralmente menor que 100 ml em adultos', 'source': 'Semiologia Médica UFOP'},
{'name': 'onicofagia', 'description': 'hábito de roer as unhas', 'source': 'Rômulo Passos'},
{'name': 'onicólise', 'description': 'Descolamento da unha do leito ungueal, a partir de sua ligação distal ou lateral', 'source': 'Semiologia Médica UFOP'},
{'name': 'onicomalácia', 'description': 'Unha de consistência amolecida e friável. Sugere sinal de doenças sistêmicas', 'source': 'Semiologia Médica UFOP'},
{'name': 'ooforite', 'description': 'Inflamação do ovário', 'source': 'Semiologia Médica UFOP'},
{'name': 'orquite', 'description': 'Processo inflamatório do testículo', 'source': 'Semiologia Médica UFOP'},
{'name': 'ortopnéia', 'description': 'Dificuldade para respirar quando o paciente está deitado. Melhora quando o paciente se senta, mantendo o tronco ligeiramente fletido', 'source': 'Semiologia Médica UFOP'},
{'name': 'osteomalácia', 'description': 'Paciente apresenta amolecimento e curvatura gradual dos ossos com sintomatologia dolorosa de intensidade variável. Resultado da calcificação deficiente em virtude da deficiência de vitamina D. É também conhecida como Raquitismo do adulto', 'source': 'Semiologia Médica UFOP'},
{'name': 'otalgia', 'description': 'Dor de ouvido', 'source': 'Rômulo Passos'},
{'name': 'otorragia', 'description': 'Sangramento expelido pelo ouvido', 'source': 'Semiologia Médica UFOP'},
{'name': 'otorréia', 'description': 'saída de secreção do ouvido', 'source': 'Semiologia Médica UFOP'},
{'name': 'palpitação', 'description': 'Percepção subjetica e incômoda de batimento acelerado ou irregular do coração', 'source': 'Semiologia Médica UFOP'},
{'name': 'pápula', 'description': 'lesão sólida, elevada, apresentando até 1 cm de diâmetro', 'source': 'Semiologia Médica UFOP'},
{'name': 'parafimose', 'description': 'o prepúcio é retraído e fixo', 'source': 'Rômulo Passos'},
{'name': 'paralisia de Bell' , 'description': 'Acometimento que ocorre no nervo facial que leva à fraqueza repentina ou à paralisia dos músculos de um dos lados da face', 'source': 'Semiologia Médica UFOP'},
{'name': 'paraplegia', 'description': 'Paralisia completa de dois segmentos simétricos do corpo, geralmente dos membros inferiores', 'source': 'Semiologia Médica UFOP'},
{'name': 'paresia', 'description': 'Perda parcial da motricidade, diminuição da força muscular', 'source': 'Semiologia Médica UFOP'},
{'name': 'parestesia', 'description': 'Aparecimento de sensação anormal e mal definidas, sem prévia estimulação. Dormência e formigamento são os representantes mais significativos da parestesia', 'source': 'Semiologia Médica UFOP'},
{'name': 'paroníquia', 'description': 'É uma infecção da pele que situa-se ao redor das unhas dos dedos das mãos ou dos pés', 'source': 'Semiologia Médica UFOP'},
{'name': 'pectorilóquia', 'description': 'Palavra pode ser ouvida com nitidez durante o processo de ausculta pulmonar', 'source': 'Semiologia Médica UFOP'},
{'name': 'pênfigo', 'description': 'Denominação geral a um grupo de doenças autoimunes, pouco frequentes, consistindo em dermatoses crônicas, recidivastes e algumas vezes fatais. São caracterizadas clinicamente pelo aparecimento de sucessivos grupos de vesículas e bolhas, inicialmente na mucosa bucal ou orofaríngea e, depois, na pele aparentemente sadia. As bolhas se rompem deixando uma zona erodida, posteriormente recoberta por crostas. A epiderme descola-se facilmente do plano subjacente', 'source': 'Semiologia Médica UFOP'},
{'name': 'petéquias', 'description': 'pequenas hemorragias puntiformes de 1 a 3 mm, arredondadas e discretas, com cor púrpura ou marrom', 'source': 'Rômulo Passos'},
{'name': 'pinguécula', 'description': 'nódulos elevados e amarelados que surgem a partir de um espessamento da conjuntiva bulbar pela exposição prolongada ao sol, vento e poeira', 'source': 'Rômulo Passos'},
{'name': 'pirexia', 'description': 'aumento da temperatura corporal acima dos níveis normais para o indivíduo', 'source': 'Rômulo Passos'},
{'name': 'pirose', 'description': 'Sensação de calor ou queimação no estômago. Conhecida como azia', 'source': 'Semiologia Médica UFOP'},
{'name': 'piúria', 'description': 'Presença de pus na urina', 'source': 'Rômulo Passos'},
{'name': 'plegia', 'description': 'Perda de força muscular ou paralisia', 'source': 'Semiologia Médica UFOP'},
{'name': 'pletória', 'description': 'Aumento local ou geral da massa sanguínea. Quando local pode ser denominado de congestão', 'source': 'Semiologia Médica UFOP'},
{'name': 'polaciúria', 'description': 'Aumento da frequência urinária, sem relação com o volume de urina excretado'},
{'name': 'polidactilia', 'description': 'presença de dígitos extras', 'source': 'Rômulo Passos'},
{'name': 'polidipsia', 'description': 'Termo que refere a sede excessiva', 'source': 'Semiologia Médica UFOP'},
{'name': 'polifagia', 'description': 'Fome excessiva', 'source': 'Semiologia Médica UFOP'},
{'name': 'poliúria', 'description': 'Aumento no volume normal de urina excretado nas 24 horas', 'source': 'Semiologia Médica UFOP'},
{'name': 'presbiacusia', 'description': 'é uma perda sensorioneural gradual causada pela degeneração na orelha interna que progride lentamente após a quinta década', 'source': 'Rômulo Passos'},
{'name': 'presbiopia', 'description': 'diminuição do poder de acomodação visual com o envelhecimento', 'source': 'Rômulo Passos'},
{'name': 'priapismo', 'description': 'Ereção prolongada, não associada com estimulação sexual e geralmente dolorosa', 'source': 'Semiologia Médica UFOP'},
{'name': 'proctite', 'description': 'Inflamação da mucosa do reto', 'source': 'Semiologia Médica UFOP'},
{'name': 'pródromo', 'description': 'Manifestação clínica ou sintomática que antecede uma doença', 'source': 'Semiologia Médica UFOP'},
{'name': 'proptose', 'description': 'Deslocamento de um órgão para frente', 'source': 'Semiologia Médica UFOP'},
{'name': 'pterígio', 'description': 'Tecido fibrovascular recoberto pela conjuntiva ocular, de forma triangular e geralmente localizado no canto interno do olho', 'source': 'Semiologia Médica UFOP'},
{'name': 'ptose palpebral' , 'description': 'Queda da pálpebra associada a lesão do nervo oculomotor', 'source': 'Semiologia Médica UFOP'},
{'name': 'pústula', 'description': 'Vesícula de conteúdo purulento', 'source': 'Semiologia Médica UFOP'},
{'name': 'puxo', 'description': 'Contração espasmódica do reto que precede as evacuações', 'source': 'Semiologia Médica UFOP'},
{'name': 'queilite', 'description': 'rachadura nos cantos da boca', 'source': 'Rômulo Passos'},
{'name': 'queloide', 'description': 'é uma cicatriz hipertrófica onde o nível da pele resultante está elevado pelo excesso de tecido cicatricial, que invade além do local original da lesão', 'source': 'Rômulo Passos'},
{'name': 'queratose', 'description': 'são áreas elevadas e espessadas de pigmentação que aparecem com crostas, camadas e verrugas', 'source': 'Rômulo Passos'},
{'name': 'rash', 'description': 'Erupção de coloração avermelhada, eritematosa em pele como resultado de uma reação alérgica ou infecção. Sinônimo de exantema', 'source': 'Semiologia Médica UFOP'},
{'name': 'regurgitação', 'description': 'Retorno à boca ou garganta do alimento recém ingerido sem esforço de vômito, ocasionado por refluxo intenso', 'source': 'Semiologia Médica UFOP'},
{'name': 'ressecção', 'description': 'Extirpação cirúrgica parcial ou total de um órgão', 'source': 'Semiologia Médica UFOP'},
{'name': 'rinite', 'description': 'Inflamação do nariz', 'source': 'Semiologia Médica UFOP'},
{'name': 'rinorréia', 'description': 'Secreção nasal', 'source': 'Semiologia Médica UFOP'},
{'name': 'riso sardônico', 'description': 'é um aspeto da face quando os músculos da cara se contraem espasmodicamente, dando uma expressão de riso sarcástico, e que pode verificar-se nos doentes com tétano', 'source': 'Infopedia'},
{'name': 'salicismo', 'description': 'Intoxicação por ácido salicílico, aspirina', 'source': 'Semiologia Médica UFOP'},
{'name': 'sepse', 'description': 'antiga septicemia. Disseminação de bactérias patogênicas partir de um foco de infecção através da circulação sistêmica', 'source': 'Semiologia Médica UFOP'},
{'name': 'sialorréia', 'description': 'Aumento da secreção de saliva', 'source': 'Semiologia Médica UFOP'},
{'name': 'sialosquise', 'description': 'Diminuição da secreção de saliva',},
{'name': 'sinal patognomônico' , 'description': 'Manifestação específica de uma entidade patológica', 'source': 'Semiologia Médica UFOP'},
{'name': 'síncope', 'description': 'perda súbita da consciência, geralmente acompanhada de perda do tônus postural, desmaio', 'source': 'Semiologia Médica UFOP'},
{'name': 'sindactilia', 'description': 'presença de dedos ligados', 'source': 'Rômulo Passos'},
{'name': 'síndrome', 'description': 'Conjunto de sinais e sintomas de mesma marcha evolutiva, porém de causas diversas, que caracterizam um estado mórbido e que se repete na população', 'source': 'Semiologia Médica UFOP'},
{'name': 'sintoma', 'description': 'Manifestação subjetiva de uma doença. Também é uma percepção normal que uma pessoa tem de seu próprio corpo', 'source': 'Semiologia Médica UFOP'},
{'name': 'sinusite', 'description': 'inflamação dos seios paranasais', 'source': 'Rômulo Passos'},
{'name': 'supuração', 'description': 'Presença de secreção purulenta', 'source': 'Semiologia Médica UFOP'},
{'name': 'taquicardia', 'description': 'Aceleração dos batimentos cardíacos, comumente considerado acima de 100 batimentos por minuto', 'source': 'Semiologia Médica UFOP'},
{'name': 'taquipnéia', 'description': ' Respiração rápida e superficial. Frequência respiratória aumentada, maior que 20 irpm', 'source': 'Rômulo Passos'},
{'name': 'telangiectasia', 'description': 'vasos sanguíneos dilatados e permanentemente aumentados que são visíveis na superfície da pele', 'source': 'Rômulo Passos'},
{'name': 'tenesmo', 'description': 'Espasmo doloroso do esfíncter anal ou vesical com desejo urgente de defecar ou urinar. Há eliminação de quantidade mínima de fezes ou urina', 'source': 'Semiologia Médica UFOP'},
{'name': 'tique', 'description': 'Movimento repetido irregular espasmódico', 'source': 'Semiologia Médica UFOP'},
{'name': 'trepanação', 'description': 'É uma intervenção cirúrgica, em que um buraco (fenestra) é aberto no crânio humano', 'source': 'Semiologia Médica UFOP'},
{'name': 'tricotilomania', 'description': 'perda traumática auto induzida do cabelo, usualmente como resultado do retorcimento ou arrancamento compulsivo', 'source': 'Rômulo Passos'},
{'name': 'tricotomia', 'description': 'é um procedimento pré-cirúrgico que tem como objetivo remover os pelos da região a ser cortada para facilitar a visualização da região pelo médico e evitar possíveis infecções após a cirurgia e, consequentemente, complicações para o paciente', 'source': 'site tua saúde'},
{'name': 'trismo', 'description': 'considerado a limitação de abertura bucal cuja etiologia está associada a diversos fatores tais como disfunção temporomandibular, complicações exodônticas, lesão cancerosas, entre outras', 'source': 'Biblioteca Virtual da Saúde'},
{'name': 'tumor', 'description': 'Lesão sólida, elevada, com mais de 3 cm de diâmetro', 'source': 'Semiologia Médica UFOP'},
{'name': 'úlcera', 'description': 'perda de resvestimento epitelial deixando o tecido conjuntivo ou derme desnuda', 'source': 'Semiologia Médica UFOP'},
{'name': 'unhas de Lindsay', 'description': 'Unhas apresentando metade proximal de cor branca, 20-50% distal vermelho. Ocorre na insuficiência renal', 'source': 'Semiologia Médica UFOP'},
{'name': 'unhas hipocráticas', 'description': 'Unhas recurvadas, em padrão de vidro de relógio, com baqueteamento digital', 'source': 'Semiologia Médica UFOP'},
{'name': 'uretrite', 'description': 'inflamação da uretra', 'source': 'Rômulo Passos'},
{'name': 'urtica', 'description': 'Pápula eritêmato-edematosa, de duração efêmera que tem frequentemente a borda irregular com aspecto de irregular. Pode coalescer e formar placa eritematosa', 'source': 'Semiologia Médica UFOP'},
{'name': 'urticária', 'description': 'pápulas que coalescem para forma uma extensa reação, intensamente pruriginosa', 'source': 'Rômulo Passos'},
{'name': 'vaginismo', 'description': 'Contração involuntária da vagina', 'source': 'Semiologia Médica UFOP'},
{'name': 'vaginite', 'description': 'Inflamação da mucosa que reveste a vagina', 'source': 'Semiologia Médica UFOP'},
{'name': 'vegetações', 'description': 'Projeções sólidas, digitiformes, moles, por vezes sangrantes e de tamanhos variáveis', 'source': 'Semiologia Médica UFOP'},
{'name': 'verruga', 'description': 'Vegetação de superfície queratótica, de aspecto irregular', 'source': 'Semiologia Médica UFOP'},
{'name': 'vertigem', 'description': 'Sensação de rotação do organismo em relação ao ambiente ou do ambiente em relação ao organismo por alteração do sistema laberíntico ou cerebelar', 'source': 'Semiologia Médica UFOP'},
{'name': 'vesícula', 'description': 'Coleção líquida, elevada, com diâmetro de até 1 cm', 'source': 'Semiologia Médica UFOP'},
{'name': 'xantelasma', 'description': 'manchas ou placas amarelas que surge na região das pálpebras, provocada pelo depósito de lipídeos', 'source': 'Semiologia Médica UFOP'},
{'name': 'xantoderma', 'description': 'Termo para designar paciente nipônico, pele de cor amarela', 'source': 'Semiologia Médica UFOP'},
{'name': 'xantomatose', 'description': 'Acúmulo de excesso de lipídios no organismo por alteração metabólica ou formação de tumores', 'source': 'Semiologia Médica UFOP'},
{'name': 'xeroftalmia', 'description': 'Perda da secreção lacrimal e caracterização de ressecamento excessivo das mucosas que revestem o olho', 'source': 'Semiologia Médica UFOP'},
{'name': 'xerostomia', 'description': 'Ressecamento da boca em resultado pela secreção insuficiente ou ausente das glândulas salivares', 'source': 'Semiologia Médica UFOP'}
]
